//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/dash/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JacksonAnnotationValue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJacksonAnnotationValue")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationJacksonAnnotationValue
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJacksonAnnotationValue 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJacksonAnnotationValue 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationJacksonAnnotationValue

#if !defined (ComFasterxmlJacksonAnnotationJacksonAnnotationValue_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationJacksonAnnotationValue || defined(INCLUDE_ComFasterxmlJacksonAnnotationJacksonAnnotationValue))
#define ComFasterxmlJacksonAnnotationJacksonAnnotationValue_

@class IOSClass;

@protocol ComFasterxmlJacksonAnnotationJacksonAnnotationValue < JavaObject >

- (IOSClass *)valueFor;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJacksonAnnotationValue)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJacksonAnnotationValue)

#endif

#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJacksonAnnotationValue")
