//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JacksonAnnotationsInside.java
//

#ifndef _ComFasterxmlJacksonAnnotationJacksonAnnotationsInside_H_
#define _ComFasterxmlJacksonAnnotationJacksonAnnotationsInside_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJacksonAnnotationsInside < JavaLangAnnotationAnnotation >

@end

@interface ComFasterxmlJacksonAnnotationJacksonAnnotationsInside : NSObject < ComFasterxmlJacksonAnnotationJacksonAnnotationsInside >

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJacksonAnnotationsInside)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJacksonAnnotationsInside)

#endif // _ComFasterxmlJacksonAnnotationJacksonAnnotationsInside_H_
