//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JacksonAnnotation.java
//

#ifndef _ComFasterxmlJacksonAnnotationJacksonAnnotation_H_
#define _ComFasterxmlJacksonAnnotationJacksonAnnotation_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJacksonAnnotation < JavaLangAnnotationAnnotation >

@end

@interface ComFasterxmlJacksonAnnotationJacksonAnnotation : NSObject < ComFasterxmlJacksonAnnotationJacksonAnnotation >

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJacksonAnnotation_init() {}

#endif // _ComFasterxmlJacksonAnnotationJacksonAnnotation_H_
