//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/dash/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JacksonAnnotationValue.java
//

#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotationValue.h"

@interface ComFasterxmlJacksonAnnotationJacksonAnnotationValue : NSObject

@end

@implementation ComFasterxmlJacksonAnnotationJacksonAnnotationValue

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LIOSClass;", 0x401, -1, -1, -1, 0, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(valueFor);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "()Ljava/lang/Class<TA;>;", "<A::Ljava/lang/annotation/Annotation;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJacksonAnnotationValue = { "JacksonAnnotationValue", "com.fasterxml.jackson.annotation", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, 1, -1 };
  return &_ComFasterxmlJacksonAnnotationJacksonAnnotationValue;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJacksonAnnotationValue)
