//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonIdentityInfo.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonIdentityInfo_H_
#define _ComFasterxmlJacksonAnnotationJsonIdentityInfo_H_

@class IOSClass;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonIdentityInfo < JavaLangAnnotationAnnotation >

@property (readonly) NSString *property;
@property (readonly) IOSClass *generator;
@property (readonly) IOSClass *resolver;
@property (readonly) IOSClass *scope;


@end

@interface ComFasterxmlJacksonAnnotationJsonIdentityInfo : NSObject < ComFasterxmlJacksonAnnotationJsonIdentityInfo > {
 @private
  NSString *property;
  IOSClass *generator;
  IOSClass *resolver;
  IOSClass *scope;
}

- (id)initWithGenerator:(IOSClass *)generator_ withProperty:(NSString *)property_ withResolver:(IOSClass *)resolver_ withScope:(IOSClass *)scope_;

+ (NSString *)propertyDefault;
+ (IOSClass *)resolverDefault;
+ (IOSClass *)scopeDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonIdentityInfo_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonIdentityInfo_H_
