//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonIgnoreType.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonIgnoreType_H_
#define _ComFasterxmlJacksonAnnotationJsonIgnoreType_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonIgnoreType < JavaLangAnnotationAnnotation >

@property (readonly) jboolean value;

@end

@interface ComFasterxmlJacksonAnnotationJsonIgnoreType : NSObject < ComFasterxmlJacksonAnnotationJsonIgnoreType > {
 @private
  jboolean value_;
}

- (instancetype)initWithValue:(jboolean)value__;

+ (jboolean)valueDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonIgnoreType)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonIgnoreType)

#endif // _ComFasterxmlJacksonAnnotationJsonIgnoreType_H_
