//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonIgnoreProperties.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonIgnoreProperties_H_
#define _ComFasterxmlJacksonAnnotationJsonIgnoreProperties_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonIgnoreProperties < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;
@property (readonly) jboolean ignoreUnknown;


@end

@interface ComFasterxmlJacksonAnnotationJsonIgnoreProperties : NSObject < ComFasterxmlJacksonAnnotationJsonIgnoreProperties > {
 @private
  IOSObjectArray *value;
  jboolean ignoreUnknown;
}

- (instancetype)initWithIgnoreUnknown:(jboolean)ignoreUnknown_ withValue:(IOSObjectArray *)value_;

+ (IOSObjectArray *)valueDefault;
+ (jboolean)ignoreUnknownDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonIgnoreProperties_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonIgnoreProperties_H_
