//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/ubuntu/projects/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonUnwrapped.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonUnwrapped.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

__attribute__((unused)) static IOSObjectArray *ComFasterxmlJacksonAnnotationJsonUnwrapped__Annotations$0(void);

@implementation ComFasterxmlJacksonAnnotationJsonUnwrapped

@synthesize enabled = enabled_;
@synthesize prefix = prefix_;
@synthesize suffix = suffix_;

+ (jboolean)enabledDefault {
  return true;
}

+ (NSString *)prefixDefault {
  return @"";
}

+ (NSString *)suffixDefault {
  return @"";
}

- (IOSClass *)annotationType {
  return ComFasterxmlJacksonAnnotationJsonUnwrapped_class_();
}

- (NSString *)description {
  return @"@com.fasterxml.jackson.annotation.JsonUnwrapped()";
}

- (void)dealloc {
  RELEASE_(prefix_);
  RELEASE_(suffix_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(enabled);
  methods[1].selector = @selector(prefix);
  methods[2].selector = @selector(suffix);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "enabled_", "Z", .constantValue.asLong = 0, 0x1000, -1, -1, -1, -1 },
    { "prefix_", "LNSString;", .constantValue.asLong = 0, 0x1000, -1, -1, -1, -1 },
    { "suffix_", "LNSString;", .constantValue.asLong = 0, 0x1000, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { (void *)&ComFasterxmlJacksonAnnotationJsonUnwrapped__Annotations$0 };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonUnwrapped = { "JsonUnwrapped", "com.fasterxml.jackson.annotation", ptrTable, methods, fields, 7, 0x2609, 3, 3, -1, -1, -1, -1, 0 };
  return &_ComFasterxmlJacksonAnnotationJsonUnwrapped;
}

@end

id<ComFasterxmlJacksonAnnotationJsonUnwrapped> create_ComFasterxmlJacksonAnnotationJsonUnwrapped(jboolean enabled, NSString *prefix, NSString *suffix) {
  ComFasterxmlJacksonAnnotationJsonUnwrapped *self = AUTORELEASE([[ComFasterxmlJacksonAnnotationJsonUnwrapped alloc] init]);
  self->enabled_ = enabled;
  self->prefix_ = RETAIN_(prefix);
  self->suffix_ = RETAIN_(suffix);
  return self;
}

IOSObjectArray *ComFasterxmlJacksonAnnotationJsonUnwrapped__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationTarget([IOSObjectArray arrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, ANNOTATION_TYPE), JreLoadEnum(JavaLangAnnotationElementType, FIELD), JreLoadEnum(JavaLangAnnotationElementType, METHOD), JreLoadEnum(JavaLangAnnotationElementType, PARAMETER) } count:4 type:JavaLangAnnotationElementType_class_()]), create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, RUNTIME)), create_ComFasterxmlJacksonAnnotationJacksonAnnotation() } count:3 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonUnwrapped)
