//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonValue.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonValue_H_
#define _ComFasterxmlJacksonAnnotationJsonValue_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonValue < JavaLangAnnotationAnnotation >

@property (readonly) jboolean value;

@end

@interface ComFasterxmlJacksonAnnotationJsonValue : NSObject < ComFasterxmlJacksonAnnotationJsonValue > {
 @private
  jboolean value_;
}

- (instancetype)initWithValue:(jboolean)value__;

+ (jboolean)valueDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonValue)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonValue)

#endif // _ComFasterxmlJacksonAnnotationJsonValue_H_
