//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonProperty.java
//


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonProperty.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

NSString *ComFasterxmlJacksonAnnotationJsonProperty_USE_DEFAULT_NAME_ = @"";

@implementation ComFasterxmlJacksonAnnotationJsonProperty

@synthesize value = value_;
@synthesize required = required_;
@synthesize index = index_;
@synthesize defaultValue = defaultValue_;

- (instancetype)initWithDefaultValue:(NSString *)defaultValue__ withIndex:(jint)index__ withRequired:(jboolean)required__ withValue:(NSString *)value__ {
  if ((self = [super init])) {
    self->defaultValue_ = RETAIN_(defaultValue__);
    self->index_ = index__;
    self->required_ = required__;
    self->value_ = RETAIN_(value__);
  }
  return self;
}

+ (NSString *)valueDefault {
  return ComFasterxmlJacksonAnnotationJsonProperty_USE_DEFAULT_NAME_;
}

+ (jboolean)requiredDefault {
  return NO;
}

+ (jint)indexDefault {
  return ComFasterxmlJacksonAnnotationJsonProperty_INDEX_UNKNOWN;
}

+ (NSString *)defaultValueDefault {
  return @"";
}

- (IOSClass *)annotationType {
  return ComFasterxmlJacksonAnnotationJsonProperty_class_();
}

- (NSString *)description {
  return @"@com.fasterxml.jackson.annotation.JsonProperty()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_ANNOTATION_TYPE(), JavaLangAnnotationElementTypeEnum_get_FIELD(), JavaLangAnnotationElementTypeEnum_get_METHOD(), JavaLangAnnotationElementTypeEnum_get_PARAMETER() } count:4 type:NSObject_class_()]] autorelease], [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] autorelease], [[[ComFasterxmlJacksonAnnotationJacksonAnnotation alloc] init] autorelease] } count:3 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "value", "value", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "valueDefault", "value", "Ljava.lang.String;", 0x100a, NULL, NULL },
    { "required", "required", "Z", 0x401, NULL, NULL },
    { "requiredDefault", "required", "Z", 0x100a, NULL, NULL },
    { "index", "index", "I", 0x401, NULL, NULL },
    { "indexDefault", "index", "I", 0x100a, NULL, NULL },
    { "defaultValue", "defaultValue", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "defaultValueDefault", "defaultValue", "Ljava.lang.String;", 0x100a, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "USE_DEFAULT_NAME_", NULL, 0x19, "Ljava.lang.String;", &ComFasterxmlJacksonAnnotationJsonProperty_USE_DEFAULT_NAME_, NULL,  },
    { "INDEX_UNKNOWN_", NULL, 0x19, "I", NULL, NULL, .constantValue.asInt = ComFasterxmlJacksonAnnotationJsonProperty_INDEX_UNKNOWN },
  };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonProperty = { 2, "JsonProperty", "com.fasterxml.jackson.annotation", NULL, 0x2609, 8, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComFasterxmlJacksonAnnotationJsonProperty;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonProperty)
