//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonInclude.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonInclude_H_
#define _ComFasterxmlJacksonAnnotationJsonInclude_H_

@class ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum;

#import "JreEmulation.h"
#include "java/lang/Enum.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonInclude < JavaLangAnnotationAnnotation >

@property (readonly) ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *value;
@property (readonly) ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *content;


@end

@interface ComFasterxmlJacksonAnnotationJsonInclude : NSObject < ComFasterxmlJacksonAnnotationJsonInclude > {
 @private
  ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *value;
  ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *content;
}

- (id)initWithContent:(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)content_ withValue:(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)value_;

+ (ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)valueDefault;
+ (ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)contentDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonInclude_init() {}

typedef enum {
  ComFasterxmlJacksonAnnotationJsonInclude_Include_ALWAYS = 0,
  ComFasterxmlJacksonAnnotationJsonInclude_Include_NON_NULL = 1,
  ComFasterxmlJacksonAnnotationJsonInclude_Include_NON_DEFAULT = 2,
  ComFasterxmlJacksonAnnotationJsonInclude_Include_NON_EMPTY = 3,
} ComFasterxmlJacksonAnnotationJsonInclude_Include;

@interface ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum : JavaLangEnum < NSCopying > {
}
+ (IOSObjectArray *)values;
+ (ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal;
@end

FOUNDATION_EXPORT BOOL ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initialized;
J2OBJC_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum)

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values[];

#define ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_ALWAYS ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values[ComFasterxmlJacksonAnnotationJsonInclude_Include_ALWAYS]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum, ALWAYS, ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)

#define ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_NULL ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values[ComFasterxmlJacksonAnnotationJsonInclude_Include_NON_NULL]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum, NON_NULL, ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)

#define ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_DEFAULT ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values[ComFasterxmlJacksonAnnotationJsonInclude_Include_NON_DEFAULT]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum, NON_DEFAULT, ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)

#define ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_EMPTY ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values[ComFasterxmlJacksonAnnotationJsonInclude_Include_NON_EMPTY]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum, NON_EMPTY, ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)

#endif // _ComFasterxmlJacksonAnnotationJsonInclude_H_
