//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonSubTypes.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonSubTypes_H_
#define _ComFasterxmlJacksonAnnotationJsonSubTypes_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class IOSObjectArray;

@protocol ComFasterxmlJacksonAnnotationJsonSubTypes < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;

@end

@interface ComFasterxmlJacksonAnnotationJsonSubTypes : NSObject < ComFasterxmlJacksonAnnotationJsonSubTypes > {
 @private
  IOSObjectArray *value_;
}

- (instancetype)initWithValue:(IOSObjectArray *)value__;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonSubTypes)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonSubTypes)

@protocol ComFasterxmlJacksonAnnotationJsonSubTypes_Type < JavaLangAnnotationAnnotation >

@property (readonly) IOSClass *value;
@property (readonly) NSString *name;

@end

@interface ComFasterxmlJacksonAnnotationJsonSubTypes_Type : NSObject < ComFasterxmlJacksonAnnotationJsonSubTypes_Type > {
 @private
  IOSClass *value_;
  NSString *name_;
}

- (instancetype)initWithName:(NSString *)name__ withValue:(IOSClass *)value__;

+ (NSString *)nameDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonSubTypes_Type)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonSubTypes_Type)

#endif // _ComFasterxmlJacksonAnnotationJsonSubTypes_H_
