//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonProperty.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonProperty_H_
#define _ComFasterxmlJacksonAnnotationJsonProperty_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

#define ComFasterxmlJacksonAnnotationJsonProperty_INDEX_UNKNOWN -1

@protocol ComFasterxmlJacksonAnnotationJsonProperty < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;
@property (readonly) jboolean required;
@property (readonly) jint index;
@property (readonly) NSString *defaultValue;

@end

@interface ComFasterxmlJacksonAnnotationJsonProperty : NSObject < ComFasterxmlJacksonAnnotationJsonProperty > {
 @private
  NSString *value_;
  jboolean required_;
  jint index_;
  NSString *defaultValue_;
}

- (instancetype)initWithDefaultValue:(NSString *)defaultValue__ withIndex:(jint)index__ withRequired:(jboolean)required__ withValue:(NSString *)value__;

+ (NSString *)valueDefault;
+ (jboolean)requiredDefault;
+ (jint)indexDefault;
+ (NSString *)defaultValueDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonProperty)

FOUNDATION_EXPORT NSString *ComFasterxmlJacksonAnnotationJsonProperty_USE_DEFAULT_NAME_;
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonProperty, USE_DEFAULT_NAME_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonProperty, INDEX_UNKNOWN, jint)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonProperty)

#endif // _ComFasterxmlJacksonAnnotationJsonProperty_H_
