//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonAnySetter.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonAnySetter_H_
#define _ComFasterxmlJacksonAnnotationJsonAnySetter_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonAnySetter < JavaLangAnnotationAnnotation >

@end

@interface ComFasterxmlJacksonAnnotationJsonAnySetter : NSObject < ComFasterxmlJacksonAnnotationJsonAnySetter >

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonAnySetter)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonAnySetter)

#endif // _ComFasterxmlJacksonAnnotationJsonAnySetter_H_
