//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonPropertyOrder.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonPropertyOrder_H_
#define _ComFasterxmlJacksonAnnotationJsonPropertyOrder_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonPropertyOrder < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;
@property (readonly) jboolean alphabetic;


@end

@interface ComFasterxmlJacksonAnnotationJsonPropertyOrder : NSObject < ComFasterxmlJacksonAnnotationJsonPropertyOrder > {
 @private
  IOSObjectArray *value;
  jboolean alphabetic;
}

- (instancetype)initWithAlphabetic:(jboolean)alphabetic_ withValue:(IOSObjectArray *)value_;

+ (IOSObjectArray *)valueDefault;
+ (jboolean)alphabeticDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonPropertyOrder_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonPropertyOrder_H_
