//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonCreator.java
//
//  Created by blangel on 4/21/15.
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonCreator.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation ComFasterxmlJacksonAnnotationJsonCreator
@synthesize mode;

- (id)initWithMode:(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)mode_ {
  if ((self = [super init])) {
    mode = RETAIN_(mode_);
  }
  return self;
}

+ (ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)modeDefault {
  return ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_get_DEFAULT();
}



- (IOSClass *)annotationType {
  return [IOSClass classWithProtocol:@protocol(ComFasterxmlJacksonAnnotationJsonCreator)];
}
+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_ANNOTATION_TYPE(), JavaLangAnnotationElementTypeEnum_get_METHOD(), JavaLangAnnotationElementTypeEnum_get_CONSTRUCTOR() } count:3 type:[[NSObject class] getClass]]] autorelease], [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] autorelease], [[[ComFasterxmlJacksonAnnotationJacksonAnnotation alloc] init] autorelease] } count:3 type:[IOSClass classWithProtocol:@protocol(JavaLangAnnotationAnnotation)]];
}


+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonCreator = { "JsonCreator", "com.fasterxml.jackson.annotation", NULL, 0x2201, 0, NULL, 0, NULL, 0, NULL};
  return &_ComFasterxmlJacksonAnnotationJsonCreator;
}

@end

BOOL ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initialized = NO;

ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values[4];

@implementation ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal {
  return [super initWithNSString:__name withInt:__ordinal];
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum class]) {
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DEFAULT = [[ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum alloc] initWithNSString:@"DEFAULT" withInt:0];
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DELEGATING = [[ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum alloc] initWithNSString:@"DELEGATING" withInt:1];
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_PROPERTIES = [[ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum alloc] initWithNSString:@"PROPERTIES" withInt:2];
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DISABLED = [[ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum alloc] initWithNSString:@"DISABLED" withInt:3];
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initialized = YES;
  }
}

+ (IOSObjectArray *)values {
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values count:4 type:[IOSClass classWithClass:[ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum class]]];
}

+ (ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)valueOfWithNSString:(NSString *)name {
  for (int i = 0; i < 4; i++) {
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *e = ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const char *superclass_type_args[] = {"Lcom.fasterxml.jackson.annotation.JsonCreator$Mode;"};
  static J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum = { "Mode", "com.fasterxml.jackson.annotation", "JsonCreator", 0x4019, 1, methods, 0, NULL, 1, superclass_type_args};
  return &_ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum;
}

@end
