//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonRootName.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonRootName")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationJsonRootName
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonRootName 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonRootName 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationJsonRootName

#if !defined (ComFasterxmlJacksonAnnotationJsonRootName_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonRootName || defined(INCLUDE_ComFasterxmlJacksonAnnotationJsonRootName))
#define ComFasterxmlJacksonAnnotationJsonRootName_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol ComFasterxmlJacksonAnnotationJsonRootName < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;
@property (readonly) NSString *namespace__;

@end

@interface ComFasterxmlJacksonAnnotationJsonRootName : NSObject < ComFasterxmlJacksonAnnotationJsonRootName > {
 @public
  NSString *value_;
  NSString *namespace___;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonRootName)

FOUNDATION_EXPORT id<ComFasterxmlJacksonAnnotationJsonRootName> create_ComFasterxmlJacksonAnnotationJsonRootName(NSString *namespace__, NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonRootName)

#endif

#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonRootName")
