//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonPropertyDescription.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonPropertyDescription_H_
#define _ComFasterxmlJacksonAnnotationJsonPropertyDescription_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonPropertyDescription < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;


@end

@interface ComFasterxmlJacksonAnnotationJsonPropertyDescription : NSObject < ComFasterxmlJacksonAnnotationJsonPropertyDescription > {
 @private
  NSString *value;
}

- (id)initWithValue:(NSString *)value_;

+ (NSString *)valueDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonPropertyDescription_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonPropertyDescription_H_
