//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonIdentityReference.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/fasterxml/jackson/annotation/JsonIdentityReference.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation ComFasterxmlJacksonAnnotationJsonIdentityReference
@synthesize alwaysAsId;

- (instancetype)initWithAlwaysAsId:(jboolean)alwaysAsId_ {
  if ((self = [super init])) {
    alwaysAsId = alwaysAsId_;
  }
  return self;
}

+ (jboolean)alwaysAsIdDefault {
  return NO;
}



- (IOSClass *)annotationType {
  return [IOSClass classWithProtocol:@protocol(ComFasterxmlJacksonAnnotationJsonIdentityReference)];
}

@end
