//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonPropertyDescription.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonPropertyDescription_H_
#define _ComFasterxmlJacksonAnnotationJsonPropertyDescription_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonPropertyDescription < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

@end

@interface ComFasterxmlJacksonAnnotationJsonPropertyDescription : NSObject < ComFasterxmlJacksonAnnotationJsonPropertyDescription > {
 @private
  NSString *value_;
}

- (instancetype)initWithValue:(NSString *)value__;

+ (NSString *)valueDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonPropertyDescription)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonPropertyDescription)

#endif // _ComFasterxmlJacksonAnnotationJsonPropertyDescription_H_
