//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonIgnoreProperties.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/fasterxml/jackson/annotation/JsonIgnoreProperties.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation ComFasterxmlJacksonAnnotationJsonIgnoreProperties
@synthesize value;
@synthesize ignoreUnknown;

- (instancetype)initWithIgnoreUnknown:(jboolean)ignoreUnknown_ withValue:(IOSObjectArray *)value_ {
  if ((self = [super init])) {
    ignoreUnknown = ignoreUnknown_;
    value = RETAIN_(value_);
  }
  return self;
}

+ (IOSObjectArray *)valueDefault {
  return [IOSObjectArray arrayWithObjects:(id[]){  } count:0 type:[IOSClass classWithClass:[NSString class]]];
}

+ (jboolean)ignoreUnknownDefault {
  return NO;
}



- (IOSClass *)annotationType {
  return [IOSClass classWithProtocol:@protocol(ComFasterxmlJacksonAnnotationJsonIgnoreProperties)];
}

@end
