//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/ubuntu/projects/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonAnySetter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonAnySetter")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationJsonAnySetter
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonAnySetter 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonAnySetter 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationJsonAnySetter

#if !defined (ComFasterxmlJacksonAnnotationJsonAnySetter_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonAnySetter || defined(INCLUDE_ComFasterxmlJacksonAnnotationJsonAnySetter))
#define ComFasterxmlJacksonAnnotationJsonAnySetter_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol ComFasterxmlJacksonAnnotationJsonAnySetter < JavaLangAnnotationAnnotation >

@end

@interface ComFasterxmlJacksonAnnotationJsonAnySetter : NSObject < ComFasterxmlJacksonAnnotationJsonAnySetter >

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonAnySetter)

FOUNDATION_EXPORT id<ComFasterxmlJacksonAnnotationJsonAnySetter> create_ComFasterxmlJacksonAnnotationJsonAnySetter(void);

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonAnySetter)

#endif

#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonAnySetter")
