//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/ubuntu/projects/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonIdentityReference.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonIdentityReference.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

__attribute__((unused)) static IOSObjectArray *ComFasterxmlJacksonAnnotationJsonIdentityReference__Annotations$0(void);

@implementation ComFasterxmlJacksonAnnotationJsonIdentityReference

@synthesize alwaysAsId = alwaysAsId_;

+ (jboolean)alwaysAsIdDefault {
  return false;
}

- (IOSClass *)annotationType {
  return ComFasterxmlJacksonAnnotationJsonIdentityReference_class_();
}

- (NSString *)description {
  return @"@com.fasterxml.jackson.annotation.JsonIdentityReference()";
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(alwaysAsId);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "alwaysAsId_", "Z", .constantValue.asLong = 0, 0x1000, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { (void *)&ComFasterxmlJacksonAnnotationJsonIdentityReference__Annotations$0 };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonIdentityReference = { "JsonIdentityReference", "com.fasterxml.jackson.annotation", ptrTable, methods, fields, 7, 0x2609, 1, 1, -1, -1, -1, -1, 0 };
  return &_ComFasterxmlJacksonAnnotationJsonIdentityReference;
}

@end

id<ComFasterxmlJacksonAnnotationJsonIdentityReference> create_ComFasterxmlJacksonAnnotationJsonIdentityReference(jboolean alwaysAsId) {
  ComFasterxmlJacksonAnnotationJsonIdentityReference *self = AUTORELEASE([[ComFasterxmlJacksonAnnotationJsonIdentityReference alloc] init]);
  self->alwaysAsId_ = alwaysAsId;
  return self;
}

IOSObjectArray *ComFasterxmlJacksonAnnotationJsonIdentityReference__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationTarget([IOSObjectArray arrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, ANNOTATION_TYPE), JreLoadEnum(JavaLangAnnotationElementType, TYPE), JreLoadEnum(JavaLangAnnotationElementType, FIELD), JreLoadEnum(JavaLangAnnotationElementType, METHOD), JreLoadEnum(JavaLangAnnotationElementType, PARAMETER) } count:5 type:JavaLangAnnotationElementType_class_()]), create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, RUNTIME)), create_ComFasterxmlJacksonAnnotationJacksonAnnotation() } count:3 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonIdentityReference)
