//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonFormat.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonFormat_H_
#define _ComFasterxmlJacksonAnnotationJsonFormat_H_

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"
#include "java/lang/annotation/Annotation.h"

@class ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum;
@class JavaUtilLocale;
@class JavaUtilTimeZone;

@protocol ComFasterxmlJacksonAnnotationJsonFormat < JavaLangAnnotationAnnotation >

@property (readonly) NSString *pattern;
@property (readonly) ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *shape;
@property (readonly) NSString *locale;
@property (readonly) NSString *timezone;

@end

@interface ComFasterxmlJacksonAnnotationJsonFormat : NSObject < ComFasterxmlJacksonAnnotationJsonFormat > {
 @private
  NSString *pattern_;
  ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *shape_;
  NSString *locale_;
  NSString *timezone_;
}

- (instancetype)initWithLocale:(NSString *)locale__ withPattern:(NSString *)pattern__ withShape:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)shape__ withTimezone:(NSString *)timezone__;

+ (NSString *)patternDefault;
+ (ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)shapeDefault;
+ (NSString *)localeDefault;
+ (NSString *)timezoneDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonFormat)

FOUNDATION_EXPORT NSString *ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_LOCALE_;
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat, DEFAULT_LOCALE_, NSString *)

FOUNDATION_EXPORT NSString *ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_TIMEZONE_;
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat, DEFAULT_TIMEZONE_, NSString *)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonFormat)

typedef NS_ENUM(NSUInteger, ComFasterxmlJacksonAnnotationJsonFormat_Shape) {
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_ANY = 0,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_SCALAR = 1,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_ARRAY = 2,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_OBJECT = 3,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER = 4,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER_FLOAT = 5,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER_INT = 6,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_STRING = 7,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_BOOLEAN = 8,
};

@interface ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum : JavaLangEnum < NSCopying >

#pragma mark Public

- (jboolean)isNumeric;

- (jboolean)isStructured;

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values();

+ (ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum)

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[];

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_ANY ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[ComFasterxmlJacksonAnnotationJsonFormat_Shape_ANY]
J2OBJC_ENUM_CONSTANT_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, ANY)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_SCALAR ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[ComFasterxmlJacksonAnnotationJsonFormat_Shape_SCALAR]
J2OBJC_ENUM_CONSTANT_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, SCALAR)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_ARRAY ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[ComFasterxmlJacksonAnnotationJsonFormat_Shape_ARRAY]
J2OBJC_ENUM_CONSTANT_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, ARRAY)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_OBJECT ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[ComFasterxmlJacksonAnnotationJsonFormat_Shape_OBJECT]
J2OBJC_ENUM_CONSTANT_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, OBJECT)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER]
J2OBJC_ENUM_CONSTANT_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, NUMBER)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_FLOAT ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER_FLOAT]
J2OBJC_ENUM_CONSTANT_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, NUMBER_FLOAT)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_INT ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER_INT]
J2OBJC_ENUM_CONSTANT_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, NUMBER_INT)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_STRING ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[ComFasterxmlJacksonAnnotationJsonFormat_Shape_STRING]
J2OBJC_ENUM_CONSTANT_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, STRING)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_BOOLEAN ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[ComFasterxmlJacksonAnnotationJsonFormat_Shape_BOOLEAN]
J2OBJC_ENUM_CONSTANT_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, BOOLEAN)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum)

@interface ComFasterxmlJacksonAnnotationJsonFormat_Value : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithComFasterxmlJacksonAnnotationJsonFormat:(id<ComFasterxmlJacksonAnnotationJsonFormat>)ann;

- (instancetype)initWithNSString:(NSString *)p
withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)sh
              withJavaUtilLocale:(JavaUtilLocale *)l
                    withNSString:(NSString *)tzStr
            withJavaUtilTimeZone:(JavaUtilTimeZone *)tz;

- (instancetype)initWithNSString:(NSString *)p
withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)sh
              withJavaUtilLocale:(JavaUtilLocale *)l
            withJavaUtilTimeZone:(JavaUtilTimeZone *)tz;

- (instancetype)initWithNSString:(NSString *)p
withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)sh
                    withNSString:(NSString *)localeStr
                    withNSString:(NSString *)tzStr;

- (JavaUtilLocale *)getLocale;

- (NSString *)getPattern;

- (ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)getShape;

- (JavaUtilTimeZone *)getTimeZone;

- (jboolean)hasLocale;

- (jboolean)hasPattern;

- (jboolean)hasShape;

- (jboolean)hasTimeZone;

- (NSString *)timeZoneAsString;

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withLocaleWithJavaUtilLocale:(JavaUtilLocale *)l;

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withPatternWithNSString:(NSString *)p;

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withShapeWithComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)s;

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withTimeZoneWithJavaUtilTimeZone:(JavaUtilTimeZone *)tz;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonFormat_Value)

FOUNDATION_EXPORT void ComFasterxmlJacksonAnnotationJsonFormat_Value_init(ComFasterxmlJacksonAnnotationJsonFormat_Value *self);

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithComFasterxmlJacksonAnnotationJsonFormat_(ComFasterxmlJacksonAnnotationJsonFormat_Value *self, id<ComFasterxmlJacksonAnnotationJsonFormat> ann);

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithComFasterxmlJacksonAnnotationJsonFormat_(id<ComFasterxmlJacksonAnnotationJsonFormat> ann) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withNSString_withNSString_(ComFasterxmlJacksonAnnotationJsonFormat_Value *self, NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, NSString *localeStr, NSString *tzStr);

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withNSString_withNSString_(NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, NSString *localeStr, NSString *tzStr) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withJavaUtilTimeZone_(ComFasterxmlJacksonAnnotationJsonFormat_Value *self, NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, JavaUtilLocale *l, JavaUtilTimeZone *tz);

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withJavaUtilTimeZone_(NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, JavaUtilLocale *l, JavaUtilTimeZone *tz) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(ComFasterxmlJacksonAnnotationJsonFormat_Value *self, NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, JavaUtilLocale *l, NSString *tzStr, JavaUtilTimeZone *tz);

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, JavaUtilLocale *l, NSString *tzStr, JavaUtilTimeZone *tz) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonFormat_Value)

#endif // _ComFasterxmlJacksonAnnotationJsonFormat_H_
