//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/ubuntu/projects/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonTypeId.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeId")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationJsonTypeId
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeId 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeId 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationJsonTypeId

#if !defined (ComFasterxmlJacksonAnnotationJsonTypeId_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeId || defined(INCLUDE_ComFasterxmlJacksonAnnotationJsonTypeId))
#define ComFasterxmlJacksonAnnotationJsonTypeId_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol ComFasterxmlJacksonAnnotationJsonTypeId < JavaLangAnnotationAnnotation >

@end

@interface ComFasterxmlJacksonAnnotationJsonTypeId : NSObject < ComFasterxmlJacksonAnnotationJsonTypeId >

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonTypeId)

FOUNDATION_EXPORT id<ComFasterxmlJacksonAnnotationJsonTypeId> create_ComFasterxmlJacksonAnnotationJsonTypeId();

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonTypeId)

#endif

#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeId")
