//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonFilter.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonFilter_H_
#define _ComFasterxmlJacksonAnnotationJsonFilter_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonFilter < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;


@end

@interface ComFasterxmlJacksonAnnotationJsonFilter : NSObject < ComFasterxmlJacksonAnnotationJsonFilter > {
 @private
  NSString *value;
}

- (id)initWithValue:(NSString *)value_;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonFilter_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonFilter_H_
