//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonUnwrapped.java
//


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonUnwrapped.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation ComFasterxmlJacksonAnnotationJsonUnwrapped

@synthesize enabled = enabled_;
@synthesize prefix = prefix_;
@synthesize suffix = suffix_;

- (instancetype)initWithEnabled:(jboolean)enabled__ withPrefix:(NSString *)prefix__ withSuffix:(NSString *)suffix__ {
  if ((self = [super init])) {
    self->enabled_ = enabled__;
    self->prefix_ = RETAIN_(prefix__);
    self->suffix_ = RETAIN_(suffix__);
  }
  return self;
}

+ (jboolean)enabledDefault {
  return YES;
}

+ (NSString *)prefixDefault {
  return @"";
}

+ (NSString *)suffixDefault {
  return @"";
}

- (IOSClass *)annotationType {
  return ComFasterxmlJacksonAnnotationJsonUnwrapped_class_();
}

- (NSString *)description {
  return @"@com.fasterxml.jackson.annotation.JsonUnwrapped()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_ANNOTATION_TYPE(), JavaLangAnnotationElementTypeEnum_get_FIELD(), JavaLangAnnotationElementTypeEnum_get_METHOD(), JavaLangAnnotationElementTypeEnum_get_PARAMETER() } count:4 type:NSObject_class_()]] autorelease], [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] autorelease], [[[ComFasterxmlJacksonAnnotationJacksonAnnotation alloc] init] autorelease] } count:3 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "enabled", "enabled", "Z", 0x401, NULL, NULL },
    { "enabledDefault", "enabled", "Z", 0x100a, NULL, NULL },
    { "prefix", "prefix", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "prefixDefault", "prefix", "Ljava.lang.String;", 0x100a, NULL, NULL },
    { "suffix", "suffix", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "suffixDefault", "suffix", "Ljava.lang.String;", 0x100a, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonUnwrapped = { 2, "JsonUnwrapped", "com.fasterxml.jackson.annotation", NULL, 0x2609, 6, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComFasterxmlJacksonAnnotationJsonUnwrapped;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonUnwrapped)
