//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonCreator.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonCreator_H_
#define _ComFasterxmlJacksonAnnotationJsonCreator_H_

@class ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum;

#import "JreEmulation.h"
#include "java/lang/Enum.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonCreator < JavaLangAnnotationAnnotation >

@property (readonly) ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *mode;


@end

@interface ComFasterxmlJacksonAnnotationJsonCreator : NSObject < ComFasterxmlJacksonAnnotationJsonCreator > {
 @private
  ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *mode;
}

- (instancetype)initWithMode:(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)mode_;

+ (ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)modeDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonCreator_init() {}

typedef NS_ENUM(NSUInteger, ComFasterxmlJacksonAnnotationJsonCreator_Mode) {
  ComFasterxmlJacksonAnnotationJsonCreator_Mode_DEFAULT = 0,
  ComFasterxmlJacksonAnnotationJsonCreator_Mode_DELEGATING = 1,
  ComFasterxmlJacksonAnnotationJsonCreator_Mode_PROPERTIES = 2,
  ComFasterxmlJacksonAnnotationJsonCreator_Mode_DISABLED = 3,
};

@interface ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum : JavaLangEnum < NSCopying > {
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values();

+ (ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_valueOfWithNSString_(NSString *name);- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initialized;
J2OBJC_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum)

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values_[];

#define ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DEFAULT ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values_[ComFasterxmlJacksonAnnotationJsonCreator_Mode_DEFAULT]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum, DEFAULT, ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)

#define ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DELEGATING ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values_[ComFasterxmlJacksonAnnotationJsonCreator_Mode_DELEGATING]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum, DELEGATING, ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)

#define ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_PROPERTIES ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values_[ComFasterxmlJacksonAnnotationJsonCreator_Mode_PROPERTIES]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum, PROPERTIES, ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)

#define ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DISABLED ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values_[ComFasterxmlJacksonAnnotationJsonCreator_Mode_DISABLED]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum, DISABLED, ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)

#endif // _ComFasterxmlJacksonAnnotationJsonCreator_H_
