//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonManagedReference.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonManagedReference_H_
#define _ComFasterxmlJacksonAnnotationJsonManagedReference_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonManagedReference < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;


@end

@interface ComFasterxmlJacksonAnnotationJsonManagedReference : NSObject < ComFasterxmlJacksonAnnotationJsonManagedReference > {
 @private
  NSString *value;
}

- (instancetype)initWithValue:(NSString *)value_;

+ (NSString *)valueDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonManagedReference_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonManagedReference_H_
