//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonIgnore.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonIgnore_H_
#define _ComFasterxmlJacksonAnnotationJsonIgnore_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonIgnore < JavaLangAnnotationAnnotation >

@property (readonly) jboolean value;


@end

@interface ComFasterxmlJacksonAnnotationJsonIgnore : NSObject < ComFasterxmlJacksonAnnotationJsonIgnore > {
 @private
  jboolean value;
}

- (instancetype)initWithValue:(jboolean)value_;

+ (jboolean)valueDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonIgnore_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonIgnore_H_
