//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonTypeInfo.java
//
//  Created by blangel on 4/21/15.
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonTypeInfo.h"
#include "java/lang/Deprecated.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation ComFasterxmlJacksonAnnotationJsonTypeInfo
@synthesize use;
@synthesize include;
@synthesize property;
@synthesize defaultImpl;
@synthesize visible;

- (id)initWithDefaultImpl:(IOSClass *)defaultImpl_ withInclude:(ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum *)include_ withProperty:(NSString *)property_ withUse:(ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum *)use_ withVisible:(BOOL)visible_ {
  if ((self = [super init])) {
    defaultImpl = RETAIN_(defaultImpl_);
    include = RETAIN_(include_);
    property = RETAIN_(property_);
    use = RETAIN_(use_);
    visible = visible_;
  }
  return self;
}

+ (ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum *)includeDefault {
  return ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_get_PROPERTY();
}

+ (NSString *)propertyDefault {
  return @"";
}

+ (IOSClass *)defaultImplDefault {
  return [IOSClass classWithClass:[ComFasterxmlJacksonAnnotationJsonTypeInfo_None class]];
}

+ (BOOL)visibleDefault {
  return NO;
}



- (IOSClass *)annotationType {
  return [IOSClass classWithProtocol:@protocol(ComFasterxmlJacksonAnnotationJsonTypeInfo)];
}
+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_ANNOTATION_TYPE(), JavaLangAnnotationElementTypeEnum_get_TYPE(), JavaLangAnnotationElementTypeEnum_get_FIELD(), JavaLangAnnotationElementTypeEnum_get_METHOD(), JavaLangAnnotationElementTypeEnum_get_PARAMETER() } count:5 type:[[NSObject class] getClass]]] autorelease], [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] autorelease], [[[ComFasterxmlJacksonAnnotationJacksonAnnotation alloc] init] autorelease] } count:3 type:[IOSClass classWithProtocol:@protocol(JavaLangAnnotationAnnotation)]];
}


+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonTypeInfo = { "JsonTypeInfo", "com.fasterxml.jackson.annotation", NULL, 0x2201, 0, NULL, 0, NULL, 0, NULL};
  return &_ComFasterxmlJacksonAnnotationJsonTypeInfo;
}

@end

BOOL ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_initialized = NO;

ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum *ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_values[5];

@implementation ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

- (id)initWithNSString:(NSString *)defProp
          withNSString:(NSString *)__name
               withInt:(int)__ordinal {
  if ((self = [super initWithNSString:__name withInt:__ordinal])) {
    ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_set__defaultPropertyName_(self, defProp);
  }
  return self;
}

- (NSString *)getDefaultPropertyName {
  return _defaultPropertyName_;
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum class]) {
    ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_NONE = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum alloc] initWithNSString:nil withNSString:@"NONE" withInt:0];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_CLASS = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum alloc] initWithNSString:@"@class" withNSString:@"CLASS" withInt:1];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_MINIMAL_CLASS = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum alloc] initWithNSString:@"@c" withNSString:@"MINIMAL_CLASS" withInt:2];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_NAME = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum alloc] initWithNSString:@"@type" withNSString:@"NAME" withInt:3];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_CUSTOM = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum alloc] initWithNSString:nil withNSString:@"CUSTOM" withInt:4];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_initialized = YES;
  }
}

+ (IOSObjectArray *)values {
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_values count:5 type:[IOSClass classWithClass:[ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum class]]];
}

+ (ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum *)valueOfWithNSString:(NSString *)name {
  for (int i = 0; i < 5; i++) {
    ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum *e = ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum_values[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "Id", NULL, 0x2, NULL },
    { "getDefaultPropertyName", NULL, "Ljava.lang.String;", 0x1, NULL },
  };
  static const char *superclass_type_args[] = {"Lcom.fasterxml.jackson.annotation.JsonTypeInfo$Id;"};
  static J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum = { "Id", "com.fasterxml.jackson.annotation", "JsonTypeInfo", 0x4019, 2, methods, 0, NULL, 1, superclass_type_args};
  return &_ComFasterxmlJacksonAnnotationJsonTypeInfo_IdEnum;
}

@end

BOOL ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_initialized = NO;

ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum *ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_values[5];

@implementation ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal {
  return [super initWithNSString:__name withInt:__ordinal];
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum class]) {
    ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_PROPERTY = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum alloc] initWithNSString:@"PROPERTY" withInt:0];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_WRAPPER_OBJECT = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum alloc] initWithNSString:@"WRAPPER_OBJECT" withInt:1];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_WRAPPER_ARRAY = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum alloc] initWithNSString:@"WRAPPER_ARRAY" withInt:2];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_EXTERNAL_PROPERTY = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum alloc] initWithNSString:@"EXTERNAL_PROPERTY" withInt:3];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_EXISTING_PROPERTY = [[ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum alloc] initWithNSString:@"EXISTING_PROPERTY" withInt:4];
    ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_initialized = YES;
  }
}

+ (IOSObjectArray *)values {
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_values count:5 type:[IOSClass classWithClass:[ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum class]]];
}

+ (ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum *)valueOfWithNSString:(NSString *)name {
  for (int i = 0; i < 5; i++) {
    ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum *e = ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum_values[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const char *superclass_type_args[] = {"Lcom.fasterxml.jackson.annotation.JsonTypeInfo$As;"};
  static J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum = { "As", "com.fasterxml.jackson.annotation", "JsonTypeInfo", 0x4019, 1, methods, 0, NULL, 1, superclass_type_args};
  return &_ComFasterxmlJacksonAnnotationJsonTypeInfo_AsEnum;
}

@end

@implementation ComFasterxmlJacksonAnnotationJsonTypeInfo_None

- (id)init {
  return [super init];
}
+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangDeprecated alloc] init] autorelease] } count:1 type:[IOSClass classWithProtocol:@protocol(JavaLangAnnotationAnnotation)]];
}


+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonTypeInfo_None = { "None", "com.fasterxml.jackson.annotation", "JsonTypeInfo", 0x409, 1, methods, 0, NULL, 0, NULL};
  return &_ComFasterxmlJacksonAnnotationJsonTypeInfo_None;
}

@end
