//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonTypeName.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonTypeName_H_
#define _ComFasterxmlJacksonAnnotationJsonTypeName_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonTypeName < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;


@end

@interface ComFasterxmlJacksonAnnotationJsonTypeName : NSObject < ComFasterxmlJacksonAnnotationJsonTypeName > {
 @private
  NSString *value;
}

- (id)initWithValue:(NSString *)value_;

+ (NSString *)valueDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonTypeName_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonTypeName_H_
