//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonSubTypes.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonSubTypes_H_
#define _ComFasterxmlJacksonAnnotationJsonSubTypes_H_

@class IOSClass;
@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonSubTypes < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;


@end

@interface ComFasterxmlJacksonAnnotationJsonSubTypes : NSObject < ComFasterxmlJacksonAnnotationJsonSubTypes > {
 @private
  IOSObjectArray *value;
}

- (id)initWithValue:(IOSObjectArray *)value_;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonSubTypes_init() {}

@protocol ComFasterxmlJacksonAnnotationJsonSubTypes_Type < JavaLangAnnotationAnnotation >

@end

#endif // _ComFasterxmlJacksonAnnotationJsonSubTypes_H_
