//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonCreator.java
//


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonCreator.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

__attribute__((unused)) static void ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *new_ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

@implementation ComFasterxmlJacksonAnnotationJsonCreator

@synthesize mode = mode_;

- (instancetype)initWithMode:(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)mode__ {
  if ((self = [super init])) {
    self->mode_ = RETAIN_(mode__);
  }
  return self;
}

+ (ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)modeDefault {
  return ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_get_DEFAULT();
}

- (IOSClass *)annotationType {
  return ComFasterxmlJacksonAnnotationJsonCreator_class_();
}

- (NSString *)description {
  return @"@com.fasterxml.jackson.annotation.JsonCreator()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_ANNOTATION_TYPE(), JavaLangAnnotationElementTypeEnum_get_METHOD(), JavaLangAnnotationElementTypeEnum_get_CONSTRUCTOR() } count:3 type:NSObject_class_()]] autorelease], [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] autorelease], [[[ComFasterxmlJacksonAnnotationJacksonAnnotation alloc] init] autorelease] } count:3 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "mode", "mode", "Lcom.fasterxml.jackson.annotation.JsonCreator$Mode;", 0x401, NULL, NULL },
    { "modeDefault", "mode", "Lcom.fasterxml.jackson.annotation.JsonCreator$Mode;", 0x100a, NULL, NULL },
  };
  static const char *inner_classes[] = {"Lcom.fasterxml.jackson.annotation.JsonCreator$Mode;"};
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonCreator = { 2, "JsonCreator", "com.fasterxml.jackson.annotation", NULL, 0x2609, 2, methods, 0, NULL, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_ComFasterxmlJacksonAnnotationJsonCreator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonCreator)

J2OBJC_INITIALIZED_DEFN(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum)

ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values_[4];

@implementation ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values() {
  ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initialize();
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values_ count:4 type:ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_class_()];
}

+ (IOSObjectArray *)values {
  return ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values();
}

+ (ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *)valueOfWithNSString:(NSString *)name {
  return ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_valueOfWithNSString_(name);
}

ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_valueOfWithNSString_(NSString *name) {
  ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initialize();
  for (int i = 0; i < 4; i++) {
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *e = ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum class]) {
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DEFAULT = new_ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(@"DEFAULT", 0);
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DELEGATING = new_ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(@"DELEGATING", 1);
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_PROPERTIES = new_ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(@"PROPERTIES", 2);
    ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DISABLED = new_ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(@"DISABLED", 3);
    J2OBJC_SET_INITIALIZED(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "DEFAULT", "DEFAULT", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonCreator$Mode;", &ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DEFAULT, NULL,  },
    { "DELEGATING", "DELEGATING", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonCreator$Mode;", &ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DELEGATING, NULL,  },
    { "PROPERTIES", "PROPERTIES", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonCreator$Mode;", &ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_PROPERTIES, NULL,  },
    { "DISABLED", "DISABLED", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonCreator$Mode;", &ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_DISABLED, NULL,  },
  };
  static const char *superclass_type_args[] = {"Lcom.fasterxml.jackson.annotation.JsonCreator$Mode;"};
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum = { 2, "Mode", "com.fasterxml.jackson.annotation", "JsonCreator", 0x4019, 0, NULL, 4, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lcom/fasterxml/jackson/annotation/JsonCreator$Mode;>;" };
  return &_ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum;
}

@end

void ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *new_ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum *self = [ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum alloc];
  ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonCreator_ModeEnum)
