//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonAnySetter.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonAnySetter_H_
#define _ComFasterxmlJacksonAnnotationJsonAnySetter_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonAnySetter < JavaLangAnnotationAnnotation >

@end

@interface ComFasterxmlJacksonAnnotationJsonAnySetter : NSObject < ComFasterxmlJacksonAnnotationJsonAnySetter >

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonAnySetter_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonAnySetter_H_
