//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonBackReference.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonBackReference_H_
#define _ComFasterxmlJacksonAnnotationJsonBackReference_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonBackReference < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

@end

@interface ComFasterxmlJacksonAnnotationJsonBackReference : NSObject < ComFasterxmlJacksonAnnotationJsonBackReference > {
 @private
  NSString *value_;
}

- (instancetype)initWithValue:(NSString *)value__;

+ (NSString *)valueDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonBackReference)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonBackReference)

#endif // _ComFasterxmlJacksonAnnotationJsonBackReference_H_
