//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonFormat.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonFormat_H_
#define _ComFasterxmlJacksonAnnotationJsonFormat_H_

@class ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum;
@class JavaUtilLocale;
@class JavaUtilTimeZone;

#import "JreEmulation.h"
#include "java/lang/Enum.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonFormat < JavaLangAnnotationAnnotation >

@property (readonly) NSString *pattern;
@property (readonly) ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *shape;
@property (readonly) NSString *locale;
@property (readonly) NSString *timezone;


@end

@interface ComFasterxmlJacksonAnnotationJsonFormat : NSObject < ComFasterxmlJacksonAnnotationJsonFormat > {
 @private
  NSString *pattern;
  ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *shape;
  NSString *locale;
  NSString *timezone;
}

- (id)initWithLocale:(NSString *)locale_ withPattern:(NSString *)pattern_ withShape:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)shape_ withTimezone:(NSString *)timezone_;

+ (NSString *)patternDefault;
+ (ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)shapeDefault;
+ (NSString *)localeDefault;
+ (NSString *)timezoneDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonFormat_init() {}

FOUNDATION_EXPORT NSString *ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_LOCALE_;
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat, DEFAULT_LOCALE_, NSString *)

FOUNDATION_EXPORT NSString *ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_TIMEZONE_;
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat, DEFAULT_TIMEZONE_, NSString *)

typedef enum {
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_ANY = 0,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_SCALAR = 1,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_ARRAY = 2,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_OBJECT = 3,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER = 4,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER_FLOAT = 5,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER_INT = 6,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_STRING = 7,
  ComFasterxmlJacksonAnnotationJsonFormat_Shape_BOOLEAN = 8,
} ComFasterxmlJacksonAnnotationJsonFormat_Shape;

@interface ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum : JavaLangEnum < NSCopying > {
}
+ (IOSObjectArray *)values;
+ (ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;

- (BOOL)isNumeric;

- (BOOL)isStructured;

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal;
@end

FOUNDATION_EXPORT BOOL ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initialized;
J2OBJC_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum)

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[];

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_ANY ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[ComFasterxmlJacksonAnnotationJsonFormat_Shape_ANY]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, ANY, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_SCALAR ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[ComFasterxmlJacksonAnnotationJsonFormat_Shape_SCALAR]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, SCALAR, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_ARRAY ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[ComFasterxmlJacksonAnnotationJsonFormat_Shape_ARRAY]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, ARRAY, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_OBJECT ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[ComFasterxmlJacksonAnnotationJsonFormat_Shape_OBJECT]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, OBJECT, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, NUMBER, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_FLOAT ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER_FLOAT]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, NUMBER_FLOAT, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_INT ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[ComFasterxmlJacksonAnnotationJsonFormat_Shape_NUMBER_INT]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, NUMBER_INT, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_STRING ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[ComFasterxmlJacksonAnnotationJsonFormat_Shape_STRING]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, STRING, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)

#define ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_BOOLEAN ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values[ComFasterxmlJacksonAnnotationJsonFormat_Shape_BOOLEAN]
J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum, BOOLEAN, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)

@interface ComFasterxmlJacksonAnnotationJsonFormat_Value : NSObject {
 @public
  NSString *pattern_;
  ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *shape_;
  JavaUtilLocale *locale_;
  NSString *timezoneStr_;
  JavaUtilTimeZone *_timezone_;
}

- (id)init;

- (id)initWithComFasterxmlJacksonAnnotationJsonFormat:(id<ComFasterxmlJacksonAnnotationJsonFormat>)ann;

- (id)initWithNSString:(NSString *)p
withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)sh
          withNSString:(NSString *)localeStr
          withNSString:(NSString *)tzStr;

- (id)initWithNSString:(NSString *)p
withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)sh
    withJavaUtilLocale:(JavaUtilLocale *)l
  withJavaUtilTimeZone:(JavaUtilTimeZone *)tz;

- (id)initWithNSString:(NSString *)p
withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)sh
    withJavaUtilLocale:(JavaUtilLocale *)l
          withNSString:(NSString *)tzStr
  withJavaUtilTimeZone:(JavaUtilTimeZone *)tz;

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withPatternWithNSString:(NSString *)p;

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withShapeWithComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)s;

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withLocaleWithJavaUtilLocale:(JavaUtilLocale *)l;

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withTimeZoneWithJavaUtilTimeZone:(JavaUtilTimeZone *)tz;

- (NSString *)getPattern;

- (ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)getShape;

- (JavaUtilLocale *)getLocale;

- (NSString *)timeZoneAsString;

- (JavaUtilTimeZone *)getTimeZone;

- (BOOL)hasShape;

- (BOOL)hasPattern;

- (BOOL)hasLocale;

- (BOOL)hasTimeZone;

- (void)copyAllFieldsTo:(ComFasterxmlJacksonAnnotationJsonFormat_Value *)other;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonFormat_Value_init() {}

J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, pattern_, NSString *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, shape_, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, locale_, JavaUtilLocale *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, timezoneStr_, NSString *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, _timezone_, JavaUtilTimeZone *)

#endif // _ComFasterxmlJacksonAnnotationJsonFormat_H_
