//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonAnyGetter.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonAnyGetter_H_
#define _ComFasterxmlJacksonAnnotationJsonAnyGetter_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonAnyGetter < JavaLangAnnotationAnnotation >

@end

@interface ComFasterxmlJacksonAnnotationJsonAnyGetter : NSObject < ComFasterxmlJacksonAnnotationJsonAnyGetter >

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonAnyGetter_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonAnyGetter_H_
