//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonTypeName.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeName")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationJsonTypeName
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeName 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeName 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationJsonTypeName

#if !defined (ComFasterxmlJacksonAnnotationJsonTypeName_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeName || defined(INCLUDE_ComFasterxmlJacksonAnnotationJsonTypeName))
#define ComFasterxmlJacksonAnnotationJsonTypeName_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol ComFasterxmlJacksonAnnotationJsonTypeName < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

@end

@interface ComFasterxmlJacksonAnnotationJsonTypeName : NSObject < ComFasterxmlJacksonAnnotationJsonTypeName > {
 @public
  NSString *value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonTypeName)

FOUNDATION_EXPORT id<ComFasterxmlJacksonAnnotationJsonTypeName> create_ComFasterxmlJacksonAnnotationJsonTypeName(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonTypeName)

#endif

#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonTypeName")
