//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/dash/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonInclude.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonInclude.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

__attribute__((unused)) static IOSObjectArray *ComFasterxmlJacksonAnnotationJsonInclude__Annotations$0(void);

__attribute__((unused)) static void ComFasterxmlJacksonAnnotationJsonInclude_Include_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationJsonInclude_Include *self, NSString *__name, jint __ordinal);

@implementation ComFasterxmlJacksonAnnotationJsonInclude

@synthesize value = value_;
@synthesize content = content_;

+ (ComFasterxmlJacksonAnnotationJsonInclude_Include *)valueDefault {
  return JreLoadEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, ALWAYS);
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_Include *)contentDefault {
  return JreLoadEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, ALWAYS);
}

- (IOSClass *)annotationType {
  return ComFasterxmlJacksonAnnotationJsonInclude_class_();
}

- (NSString *)description {
  return [NSString stringWithFormat:@"@com.fasterxml.jackson.annotation.JsonInclude(value=%@, content=%@)", value_, content_];
}

- (jboolean)isEqual:(id)obj {
  return JreAnnotationEquals(self, obj);
}

- (NSUInteger)hash {
  return JreAnnotationHashCode(self);
}

- (void)dealloc {
  RELEASE_(value_);
  RELEASE_(content_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Include;", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Include;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(value);
  methods[1].selector = @selector(content);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "value_", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x1000, -1, -1, -1, -1 },
    { "content_", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x1000, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComFasterxmlJacksonAnnotationJsonInclude_Include;LComFasterxmlJacksonAnnotationJsonInclude_Value;", (void *)&ComFasterxmlJacksonAnnotationJsonInclude__Annotations$0 };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonInclude = { "JsonInclude", "com.fasterxml.jackson.annotation", ptrTable, methods, fields, 7, 0x2609, 2, 2, -1, 0, -1, -1, 1 };
  return &_ComFasterxmlJacksonAnnotationJsonInclude;
}

@end

id<ComFasterxmlJacksonAnnotationJsonInclude> create_ComFasterxmlJacksonAnnotationJsonInclude(ComFasterxmlJacksonAnnotationJsonInclude_Include *content, ComFasterxmlJacksonAnnotationJsonInclude_Include *value) {
  ComFasterxmlJacksonAnnotationJsonInclude *self = AUTORELEASE([[ComFasterxmlJacksonAnnotationJsonInclude alloc] init]);
  self->content_ = RETAIN_(content);
  self->value_ = RETAIN_(value);
  return self;
}

IOSObjectArray *ComFasterxmlJacksonAnnotationJsonInclude__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationTarget([IOSObjectArray arrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, ANNOTATION_TYPE), JreLoadEnum(JavaLangAnnotationElementType, METHOD), JreLoadEnum(JavaLangAnnotationElementType, FIELD), JreLoadEnum(JavaLangAnnotationElementType, TYPE), JreLoadEnum(JavaLangAnnotationElementType, PARAMETER) } count:5 type:JavaLangAnnotationElementType_class_()]), create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, RUNTIME)), create_ComFasterxmlJacksonAnnotationJacksonAnnotation() } count:3 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonInclude)

J2OBJC_INITIALIZED_DEFN(ComFasterxmlJacksonAnnotationJsonInclude_Include)

ComFasterxmlJacksonAnnotationJsonInclude_Include *ComFasterxmlJacksonAnnotationJsonInclude_Include_values_[6];

@implementation ComFasterxmlJacksonAnnotationJsonInclude_Include

+ (IOSObjectArray *)values {
  return ComFasterxmlJacksonAnnotationJsonInclude_Include_values();
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_Include *)valueOfWithNSString:(NSString *)name {
  return ComFasterxmlJacksonAnnotationJsonInclude_Include_valueOfWithNSString_(name);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LComFasterxmlJacksonAnnotationJsonInclude_Include;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Include;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "ALWAYS", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "NON_NULL", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "NON_ABSENT", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "NON_EMPTY", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "NON_DEFAULT", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "USE_DEFAULTS", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x4019, -1, 7, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, ALWAYS), &JreEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, NON_NULL), &JreEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, NON_ABSENT), &JreEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, NON_EMPTY), &JreEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, NON_DEFAULT), &JreEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, USE_DEFAULTS), "LComFasterxmlJacksonAnnotationJsonInclude;", "Ljava/lang/Enum<Lcom/fasterxml/jackson/annotation/JsonInclude$Include;>;" };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonInclude_Include = { "Include", "com.fasterxml.jackson.annotation", ptrTable, methods, fields, 7, 0x4019, 2, 6, 8, -1, -1, 9, -1 };
  return &_ComFasterxmlJacksonAnnotationJsonInclude_Include;
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationJsonInclude_Include class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 6 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    for (jint i = 0; i < 6; i++) {
      ((void)(ComFasterxmlJacksonAnnotationJsonInclude_Include_values_[i] = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
      ComFasterxmlJacksonAnnotationJsonInclude_Include_initWithNSString_withInt_(e, JreEnumConstantName(ComFasterxmlJacksonAnnotationJsonInclude_Include_class_(), i), i);
    }
    J2OBJC_SET_INITIALIZED(ComFasterxmlJacksonAnnotationJsonInclude_Include)
  }
}

@end

void ComFasterxmlJacksonAnnotationJsonInclude_Include_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationJsonInclude_Include *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *ComFasterxmlJacksonAnnotationJsonInclude_Include_values() {
  ComFasterxmlJacksonAnnotationJsonInclude_Include_initialize();
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationJsonInclude_Include_values_ count:6 type:ComFasterxmlJacksonAnnotationJsonInclude_Include_class_()];
}

ComFasterxmlJacksonAnnotationJsonInclude_Include *ComFasterxmlJacksonAnnotationJsonInclude_Include_valueOfWithNSString_(NSString *name) {
  ComFasterxmlJacksonAnnotationJsonInclude_Include_initialize();
  for (int i = 0; i < 6; i++) {
    ComFasterxmlJacksonAnnotationJsonInclude_Include *e = ComFasterxmlJacksonAnnotationJsonInclude_Include_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

ComFasterxmlJacksonAnnotationJsonInclude_Include *ComFasterxmlJacksonAnnotationJsonInclude_Include_fromOrdinal(NSUInteger ordinal) {
  ComFasterxmlJacksonAnnotationJsonInclude_Include_initialize();
  if (ordinal >= 6) {
    return nil;
  }
  return ComFasterxmlJacksonAnnotationJsonInclude_Include_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonInclude_Include)

J2OBJC_INITIALIZED_DEFN(ComFasterxmlJacksonAnnotationJsonInclude_Value)

ComFasterxmlJacksonAnnotationJsonInclude_Value *ComFasterxmlJacksonAnnotationJsonInclude_Value_EMPTY;

@implementation ComFasterxmlJacksonAnnotationJsonInclude_Value

- (instancetype)initWithComFasterxmlJacksonAnnotationJsonInclude:(id<ComFasterxmlJacksonAnnotationJsonInclude>)src {
  ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_(self, src);
  return self;
}

- (instancetype)initWithComFasterxmlJacksonAnnotationJsonInclude_Include:(ComFasterxmlJacksonAnnotationJsonInclude_Include *)vi
                    withComFasterxmlJacksonAnnotationJsonInclude_Include:(ComFasterxmlJacksonAnnotationJsonInclude_Include *)ci {
  ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(self, vi, ci);
  return self;
}

- (ComFasterxmlJacksonAnnotationJsonInclude_Value *)withOverridesWithComFasterxmlJacksonAnnotationJsonInclude_Value:(ComFasterxmlJacksonAnnotationJsonInclude_Value *)overrides {
  if (overrides == nil) {
    return self;
  }
  return [((ComFasterxmlJacksonAnnotationJsonInclude_Value *) nil_chk([self withValueInclusionWithComFasterxmlJacksonAnnotationJsonInclude_Include:overrides->valueInclusion_])) withContentInclusionWithComFasterxmlJacksonAnnotationJsonInclude_Include:overrides->contentInclusion_];
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_Value *)empty {
  return ComFasterxmlJacksonAnnotationJsonInclude_Value_empty();
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_Value *)constructWithComFasterxmlJacksonAnnotationJsonInclude_Include:(ComFasterxmlJacksonAnnotationJsonInclude_Include *)valueIncl
                                                             withComFasterxmlJacksonAnnotationJsonInclude_Include:(ComFasterxmlJacksonAnnotationJsonInclude_Include *)contentIncl {
  return ComFasterxmlJacksonAnnotationJsonInclude_Value_constructWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(valueIncl, contentIncl);
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_Value *)fromWithComFasterxmlJacksonAnnotationJsonInclude:(id<ComFasterxmlJacksonAnnotationJsonInclude>)src {
  return ComFasterxmlJacksonAnnotationJsonInclude_Value_fromWithComFasterxmlJacksonAnnotationJsonInclude_(src);
}

- (ComFasterxmlJacksonAnnotationJsonInclude_Value *)withValueInclusionWithComFasterxmlJacksonAnnotationJsonInclude_Include:(ComFasterxmlJacksonAnnotationJsonInclude_Include *)incl {
  return (incl == valueInclusion_) ? self : create_ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(incl, contentInclusion_);
}

- (ComFasterxmlJacksonAnnotationJsonInclude_Value *)withContentInclusionWithComFasterxmlJacksonAnnotationJsonInclude_Include:(ComFasterxmlJacksonAnnotationJsonInclude_Include *)incl {
  return (incl == contentInclusion_) ? self : create_ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(valueInclusion_, incl);
}

- (IOSClass *)valueFor {
  return ComFasterxmlJacksonAnnotationJsonInclude_class_();
}

- (ComFasterxmlJacksonAnnotationJsonInclude_Include *)getValueInclusion {
  return valueInclusion_;
}

- (ComFasterxmlJacksonAnnotationJsonInclude_Include *)getContentInclusion {
  return contentInclusion_;
}

- (void)dealloc {
  RELEASE_(valueInclusion_);
  RELEASE_(contentInclusion_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x4, -1, 1, -1, -1, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Value;", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Value;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Value;", 0x9, 4, 1, -1, -1, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Value;", 0x9, 5, 0, -1, -1, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Value;", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Value;", 0x1, 8, 7, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, 9, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Include;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComFasterxmlJacksonAnnotationJsonInclude_Include;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComFasterxmlJacksonAnnotationJsonInclude:);
  methods[1].selector = @selector(initWithComFasterxmlJacksonAnnotationJsonInclude_Include:withComFasterxmlJacksonAnnotationJsonInclude_Include:);
  methods[2].selector = @selector(withOverridesWithComFasterxmlJacksonAnnotationJsonInclude_Value:);
  methods[3].selector = @selector(empty);
  methods[4].selector = @selector(constructWithComFasterxmlJacksonAnnotationJsonInclude_Include:withComFasterxmlJacksonAnnotationJsonInclude_Include:);
  methods[5].selector = @selector(fromWithComFasterxmlJacksonAnnotationJsonInclude:);
  methods[6].selector = @selector(withValueInclusionWithComFasterxmlJacksonAnnotationJsonInclude_Include:);
  methods[7].selector = @selector(withContentInclusionWithComFasterxmlJacksonAnnotationJsonInclude_Include:);
  methods[8].selector = @selector(valueFor);
  methods[9].selector = @selector(getValueInclusion);
  methods[10].selector = @selector(getContentInclusion);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "EMPTY", "LComFasterxmlJacksonAnnotationJsonInclude_Value;", .constantValue.asLong = 0, 0x1c, -1, 10, -1, -1 },
    { "valueInclusion_", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x14, -1, -1, -1, -1 },
    { "contentInclusion_", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", .constantValue.asLong = 0, 0x14, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComFasterxmlJacksonAnnotationJsonInclude;", "LComFasterxmlJacksonAnnotationJsonInclude_Include;LComFasterxmlJacksonAnnotationJsonInclude_Include;", "withOverrides", "LComFasterxmlJacksonAnnotationJsonInclude_Value;", "construct", "from", "withValueInclusion", "LComFasterxmlJacksonAnnotationJsonInclude_Include;", "withContentInclusion", "()Ljava/lang/Class<Lcom/fasterxml/jackson/annotation/JsonInclude;>;", &ComFasterxmlJacksonAnnotationJsonInclude_Value_EMPTY, "Ljava/lang/Object;Lcom/fasterxml/jackson/annotation/JacksonAnnotationValue<Lcom/fasterxml/jackson/annotation/JsonInclude;>;" };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonInclude_Value = { "Value", "com.fasterxml.jackson.annotation", ptrTable, methods, fields, 7, 0x9, 11, 3, 0, -1, -1, 11, -1 };
  return &_ComFasterxmlJacksonAnnotationJsonInclude_Value;
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationJsonInclude_Value class]) {
    JreStrongAssignAndConsume(&ComFasterxmlJacksonAnnotationJsonInclude_Value_EMPTY, new_ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(JreLoadEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, USE_DEFAULTS), JreLoadEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, USE_DEFAULTS)));
    J2OBJC_SET_INITIALIZED(ComFasterxmlJacksonAnnotationJsonInclude_Value)
  }
}

@end

void ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_(ComFasterxmlJacksonAnnotationJsonInclude_Value *self, id<ComFasterxmlJacksonAnnotationJsonInclude> src) {
  ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(self, [((id<ComFasterxmlJacksonAnnotationJsonInclude>) nil_chk(src)) value], [src content]);
}

ComFasterxmlJacksonAnnotationJsonInclude_Value *new_ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_(id<ComFasterxmlJacksonAnnotationJsonInclude> src) {
  J2OBJC_NEW_IMPL(ComFasterxmlJacksonAnnotationJsonInclude_Value, initWithComFasterxmlJacksonAnnotationJsonInclude_, src)
}

ComFasterxmlJacksonAnnotationJsonInclude_Value *create_ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_(id<ComFasterxmlJacksonAnnotationJsonInclude> src) {
  J2OBJC_CREATE_IMPL(ComFasterxmlJacksonAnnotationJsonInclude_Value, initWithComFasterxmlJacksonAnnotationJsonInclude_, src)
}

void ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(ComFasterxmlJacksonAnnotationJsonInclude_Value *self, ComFasterxmlJacksonAnnotationJsonInclude_Include *vi, ComFasterxmlJacksonAnnotationJsonInclude_Include *ci) {
  NSObject_init(self);
  JreStrongAssign(&self->valueInclusion_, (vi == nil) ? JreLoadEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, USE_DEFAULTS) : vi);
  JreStrongAssign(&self->contentInclusion_, (ci == nil) ? JreLoadEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, USE_DEFAULTS) : ci);
}

ComFasterxmlJacksonAnnotationJsonInclude_Value *new_ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(ComFasterxmlJacksonAnnotationJsonInclude_Include *vi, ComFasterxmlJacksonAnnotationJsonInclude_Include *ci) {
  J2OBJC_NEW_IMPL(ComFasterxmlJacksonAnnotationJsonInclude_Value, initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_, vi, ci)
}

ComFasterxmlJacksonAnnotationJsonInclude_Value *create_ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(ComFasterxmlJacksonAnnotationJsonInclude_Include *vi, ComFasterxmlJacksonAnnotationJsonInclude_Include *ci) {
  J2OBJC_CREATE_IMPL(ComFasterxmlJacksonAnnotationJsonInclude_Value, initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_, vi, ci)
}

ComFasterxmlJacksonAnnotationJsonInclude_Value *ComFasterxmlJacksonAnnotationJsonInclude_Value_empty() {
  ComFasterxmlJacksonAnnotationJsonInclude_Value_initialize();
  return ComFasterxmlJacksonAnnotationJsonInclude_Value_EMPTY;
}

ComFasterxmlJacksonAnnotationJsonInclude_Value *ComFasterxmlJacksonAnnotationJsonInclude_Value_constructWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(ComFasterxmlJacksonAnnotationJsonInclude_Include *valueIncl, ComFasterxmlJacksonAnnotationJsonInclude_Include *contentIncl) {
  ComFasterxmlJacksonAnnotationJsonInclude_Value_initialize();
  if ((valueIncl == JreLoadEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, USE_DEFAULTS)) && (contentIncl == JreLoadEnum(ComFasterxmlJacksonAnnotationJsonInclude_Include, USE_DEFAULTS))) {
    return ComFasterxmlJacksonAnnotationJsonInclude_Value_EMPTY;
  }
  return create_ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_Include_withComFasterxmlJacksonAnnotationJsonInclude_Include_(valueIncl, contentIncl);
}

ComFasterxmlJacksonAnnotationJsonInclude_Value *ComFasterxmlJacksonAnnotationJsonInclude_Value_fromWithComFasterxmlJacksonAnnotationJsonInclude_(id<ComFasterxmlJacksonAnnotationJsonInclude> src) {
  ComFasterxmlJacksonAnnotationJsonInclude_Value_initialize();
  if (src == nil) {
    return nil;
  }
  return create_ComFasterxmlJacksonAnnotationJsonInclude_Value_initWithComFasterxmlJacksonAnnotationJsonInclude_(src);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonInclude_Value)
