//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonInclude.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/fasterxml/jackson/annotation/JsonInclude.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation ComFasterxmlJacksonAnnotationJsonInclude
@synthesize value;
@synthesize content;

- (instancetype)initWithContent:(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)content_ withValue:(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)value_ {
  if ((self = [super init])) {
    content = RETAIN_(content_);
    value = RETAIN_(value_);
  }
  return self;
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)valueDefault {
  return ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_get_ALWAYS();
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)contentDefault {
  return ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_get_ALWAYS();
}



- (IOSClass *)annotationType {
  return [IOSClass classWithProtocol:@protocol(ComFasterxmlJacksonAnnotationJsonInclude)];
}

@end

BOOL ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initialized = NO;

ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values_[4];

@implementation ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  return [super initWithNSString:__name withInt:__ordinal];
}

FOUNDATION_EXPORT IOSObjectArray *ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values() {
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values_ count:4 type:[IOSClass classWithClass:[ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum class]]];
}
+ (IOSObjectArray *)values {
  return ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values();
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)valueOfWithNSString:(NSString *)name {
  return ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_valueOfWithNSString_(name);
}

ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_valueOfWithNSString_(NSString *name) {
  for (int i = 0; i < 4; i++) {
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *e = ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum class]) {
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_ALWAYS = [[ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum alloc] initWithNSString:@"ALWAYS" withInt:0];
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_NULL = [[ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum alloc] initWithNSString:@"NON_NULL" withInt:1];
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_DEFAULT = [[ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum alloc] initWithNSString:@"NON_DEFAULT" withInt:2];
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_EMPTY = [[ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum alloc] initWithNSString:@"NON_EMPTY" withInt:3];
    J2OBJC_SET_INITIALIZED(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum)
  }
}

@end
