//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonRawValue.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonRawValue_H_
#define _ComFasterxmlJacksonAnnotationJsonRawValue_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonRawValue < JavaLangAnnotationAnnotation >

@property (readonly) BOOL value;


@end

@interface ComFasterxmlJacksonAnnotationJsonRawValue : NSObject < ComFasterxmlJacksonAnnotationJsonRawValue > {
 @private
  BOOL value;
}

- (id)initWithValue:(BOOL)value_;

+ (BOOL)valueDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonRawValue_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonRawValue_H_
