//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonIgnoreType.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonIgnoreType_H_
#define _ComFasterxmlJacksonAnnotationJsonIgnoreType_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonIgnoreType < JavaLangAnnotationAnnotation >

@property (readonly) jboolean value;


@end

@interface ComFasterxmlJacksonAnnotationJsonIgnoreType : NSObject < ComFasterxmlJacksonAnnotationJsonIgnoreType > {
 @private
  jboolean value;
}

- (instancetype)initWithValue:(jboolean)value_;

+ (jboolean)valueDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonIgnoreType_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonIgnoreType_H_
