//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonPropertyOrder.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/fasterxml/jackson/annotation/JsonPropertyOrder.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation ComFasterxmlJacksonAnnotationJsonPropertyOrder
@synthesize value;
@synthesize alphabetic;

- (instancetype)initWithAlphabetic:(jboolean)alphabetic_ withValue:(IOSObjectArray *)value_ {
  if ((self = [super init])) {
    alphabetic = alphabetic_;
    value = RETAIN_(value_);
  }
  return self;
}

+ (IOSObjectArray *)valueDefault {
  return [IOSObjectArray arrayWithObjects:(id[]){  } count:0 type:[IOSClass classWithClass:[NSString class]]];
}

+ (jboolean)alphabeticDefault {
  return NO;
}



- (IOSClass *)annotationType {
  return [IOSClass classWithProtocol:@protocol(ComFasterxmlJacksonAnnotationJsonPropertyOrder)];
}

@end
