//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonInclude.java
//


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonInclude.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

__attribute__((unused)) static void ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *new_ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

@implementation ComFasterxmlJacksonAnnotationJsonInclude

@synthesize value = value_;
@synthesize content = content_;

- (instancetype)initWithContent:(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)content__ withValue:(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)value__ {
  if ((self = [super init])) {
    self->content_ = RETAIN_(content__);
    self->value_ = RETAIN_(value__);
  }
  return self;
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)valueDefault {
  return ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_get_ALWAYS();
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)contentDefault {
  return ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_get_ALWAYS();
}

- (IOSClass *)annotationType {
  return ComFasterxmlJacksonAnnotationJsonInclude_class_();
}

- (NSString *)description {
  return @"@com.fasterxml.jackson.annotation.JsonInclude()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_ANNOTATION_TYPE(), JavaLangAnnotationElementTypeEnum_get_METHOD(), JavaLangAnnotationElementTypeEnum_get_FIELD(), JavaLangAnnotationElementTypeEnum_get_TYPE(), JavaLangAnnotationElementTypeEnum_get_PARAMETER() } count:5 type:NSObject_class_()]] autorelease], [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] autorelease], [[[ComFasterxmlJacksonAnnotationJacksonAnnotation alloc] init] autorelease] } count:3 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "value", "value", "Lcom.fasterxml.jackson.annotation.JsonInclude$Include;", 0x401, NULL, NULL },
    { "valueDefault", "value", "Lcom.fasterxml.jackson.annotation.JsonInclude$Include;", 0x100a, NULL, NULL },
    { "content", "content", "Lcom.fasterxml.jackson.annotation.JsonInclude$Include;", 0x401, NULL, NULL },
    { "contentDefault", "content", "Lcom.fasterxml.jackson.annotation.JsonInclude$Include;", 0x100a, NULL, NULL },
  };
  static const char *inner_classes[] = {"Lcom.fasterxml.jackson.annotation.JsonInclude$Include;"};
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonInclude = { 2, "JsonInclude", "com.fasterxml.jackson.annotation", NULL, 0x2609, 4, methods, 0, NULL, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_ComFasterxmlJacksonAnnotationJsonInclude;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonInclude)

J2OBJC_INITIALIZED_DEFN(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum)

ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values_[4];

@implementation ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values() {
  ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initialize();
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values_ count:4 type:ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_class_()];
}

+ (IOSObjectArray *)values {
  return ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values();
}

+ (ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *)valueOfWithNSString:(NSString *)name {
  return ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_valueOfWithNSString_(name);
}

ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_valueOfWithNSString_(NSString *name) {
  ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initialize();
  for (int i = 0; i < 4; i++) {
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *e = ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum class]) {
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_ALWAYS = new_ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(@"ALWAYS", 0);
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_NULL = new_ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(@"NON_NULL", 1);
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_DEFAULT = new_ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(@"NON_DEFAULT", 2);
    ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_EMPTY = new_ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(@"NON_EMPTY", 3);
    J2OBJC_SET_INITIALIZED(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "ALWAYS", "ALWAYS", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonInclude$Include;", &ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_ALWAYS, NULL,  },
    { "NON_NULL", "NON_NULL", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonInclude$Include;", &ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_NULL, NULL,  },
    { "NON_DEFAULT", "NON_DEFAULT", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonInclude$Include;", &ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_DEFAULT, NULL,  },
    { "NON_EMPTY", "NON_EMPTY", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonInclude$Include;", &ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_NON_EMPTY, NULL,  },
  };
  static const char *superclass_type_args[] = {"Lcom.fasterxml.jackson.annotation.JsonInclude$Include;"};
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum = { 2, "Include", "com.fasterxml.jackson.annotation", "JsonInclude", 0x4019, 0, NULL, 4, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lcom/fasterxml/jackson/annotation/JsonInclude$Include;>;" };
  return &_ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum;
}

@end

void ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *new_ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum *self = [ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum alloc];
  ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonInclude_IncludeEnum)
