//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonGetter.java
//

#ifndef _ComFasterxmlJacksonAnnotationJsonGetter_H_
#define _ComFasterxmlJacksonAnnotationJsonGetter_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonGetter < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

@end

@interface ComFasterxmlJacksonAnnotationJsonGetter : NSObject < ComFasterxmlJacksonAnnotationJsonGetter > {
 @private
  NSString *value_;
}

- (instancetype)initWithValue:(NSString *)value__;

+ (NSString *)valueDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonGetter)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonGetter)

#endif // _ComFasterxmlJacksonAnnotationJsonGetter_H_
