//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonFormat.java
//


#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/JacksonAnnotation.h"
#include "com/fasterxml/jackson/annotation/JsonFormat.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"
#include "java/util/Locale.h"
#include "java/util/TimeZone.h"

__attribute__((unused)) static void ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

@interface ComFasterxmlJacksonAnnotationJsonFormat_Value () {
 @public
  NSString *pattern_;
  ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *shape_;
  JavaUtilLocale *locale_;
  NSString *timezoneStr_;
  JavaUtilTimeZone *_timezone_;
}

@end

J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, pattern_, NSString *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, shape_, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, locale_, JavaUtilLocale *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, timezoneStr_, NSString *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationJsonFormat_Value, _timezone_, JavaUtilTimeZone *)

NSString *ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_LOCALE_ = @"##default";
NSString *ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_TIMEZONE_ = @"##default";

@implementation ComFasterxmlJacksonAnnotationJsonFormat

@synthesize pattern = pattern_;
@synthesize shape = shape_;
@synthesize locale = locale_;
@synthesize timezone = timezone_;

- (instancetype)initWithLocale:(NSString *)locale__ withPattern:(NSString *)pattern__ withShape:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)shape__ withTimezone:(NSString *)timezone__ {
  if ((self = [super init])) {
    self->locale_ = RETAIN_(locale__);
    self->pattern_ = RETAIN_(pattern__);
    self->shape_ = RETAIN_(shape__);
    self->timezone_ = RETAIN_(timezone__);
  }
  return self;
}

+ (NSString *)patternDefault {
  return @"";
}

+ (ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)shapeDefault {
  return ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_get_ANY();
}

+ (NSString *)localeDefault {
  return ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_LOCALE_;
}

+ (NSString *)timezoneDefault {
  return ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_TIMEZONE_;
}

- (IOSClass *)annotationType {
  return ComFasterxmlJacksonAnnotationJsonFormat_class_();
}

- (NSString *)description {
  return @"@com.fasterxml.jackson.annotation.JsonFormat()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_ANNOTATION_TYPE(), JavaLangAnnotationElementTypeEnum_get_FIELD(), JavaLangAnnotationElementTypeEnum_get_METHOD(), JavaLangAnnotationElementTypeEnum_get_PARAMETER(), JavaLangAnnotationElementTypeEnum_get_TYPE() } count:5 type:NSObject_class_()]] autorelease], [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] autorelease], [[[ComFasterxmlJacksonAnnotationJacksonAnnotation alloc] init] autorelease] } count:3 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "pattern", "pattern", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "patternDefault", "pattern", "Ljava.lang.String;", 0x100a, NULL, NULL },
    { "shape", "shape", "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", 0x401, NULL, NULL },
    { "shapeDefault", "shape", "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", 0x100a, NULL, NULL },
    { "locale", "locale", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "localeDefault", "locale", "Ljava.lang.String;", 0x100a, NULL, NULL },
    { "timezone", "timezone", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "timezoneDefault", "timezone", "Ljava.lang.String;", 0x100a, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "DEFAULT_LOCALE_", NULL, 0x19, "Ljava.lang.String;", &ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_LOCALE_, NULL,  },
    { "DEFAULT_TIMEZONE_", NULL, 0x19, "Ljava.lang.String;", &ComFasterxmlJacksonAnnotationJsonFormat_DEFAULT_TIMEZONE_, NULL,  },
  };
  static const char *inner_classes[] = {"Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", "Lcom.fasterxml.jackson.annotation.JsonFormat$Value;"};
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonFormat = { 2, "JsonFormat", "com.fasterxml.jackson.annotation", NULL, 0x2609, 8, methods, 2, fields, 0, NULL, 2, inner_classes, NULL, NULL };
  return &_ComFasterxmlJacksonAnnotationJsonFormat;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonFormat)

J2OBJC_INITIALIZED_DEFN(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum)

ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[9];

@implementation ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum

- (jboolean)isNumeric {
  return (self == ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER) || (self == ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_INT) || (self == ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_FLOAT);
}

- (jboolean)isStructured {
  return (self == ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_OBJECT) || (self == ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_ARRAY);
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values() {
  ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initialize();
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_ count:9 type:ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_class_()];
}

+ (IOSObjectArray *)values {
  return ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values();
}

+ (ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)valueOfWithNSString:(NSString *)name {
  return ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_valueOfWithNSString_(name);
}

ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_valueOfWithNSString_(NSString *name) {
  ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initialize();
  for (int i = 0; i < 9; i++) {
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *e = ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum class]) {
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_ANY = new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(@"ANY", 0);
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_SCALAR = new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(@"SCALAR", 1);
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_ARRAY = new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(@"ARRAY", 2);
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_OBJECT = new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(@"OBJECT", 3);
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER = new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(@"NUMBER", 4);
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_FLOAT = new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(@"NUMBER_FLOAT", 5);
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_INT = new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(@"NUMBER_INT", 6);
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_STRING = new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(@"STRING", 7);
    ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_BOOLEAN = new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(@"BOOLEAN", 8);
    J2OBJC_SET_INITIALIZED(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "isNumeric", NULL, "Z", 0x1, NULL, NULL },
    { "isStructured", NULL, "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "ANY", "ANY", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", &ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_ANY, NULL,  },
    { "SCALAR", "SCALAR", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", &ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_SCALAR, NULL,  },
    { "ARRAY", "ARRAY", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", &ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_ARRAY, NULL,  },
    { "OBJECT", "OBJECT", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", &ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_OBJECT, NULL,  },
    { "NUMBER", "NUMBER", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", &ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER, NULL,  },
    { "NUMBER_FLOAT", "NUMBER_FLOAT", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", &ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_FLOAT, NULL,  },
    { "NUMBER_INT", "NUMBER_INT", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", &ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_NUMBER_INT, NULL,  },
    { "STRING", "STRING", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", &ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_STRING, NULL,  },
    { "BOOLEAN", "BOOLEAN", 0x4019, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", &ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_BOOLEAN, NULL,  },
  };
  static const char *superclass_type_args[] = {"Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;"};
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum = { 2, "Shape", "com.fasterxml.jackson.annotation", "JsonFormat", 0x4019, 2, methods, 9, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lcom/fasterxml/jackson/annotation/JsonFormat$Shape;>;" };
  return &_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum;
}

@end

void ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *new_ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *self = [ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum alloc];
  ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum)

@implementation ComFasterxmlJacksonAnnotationJsonFormat_Value

- (instancetype)init {
  ComFasterxmlJacksonAnnotationJsonFormat_Value_init(self);
  return self;
}

- (instancetype)initWithComFasterxmlJacksonAnnotationJsonFormat:(id<ComFasterxmlJacksonAnnotationJsonFormat>)ann {
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithComFasterxmlJacksonAnnotationJsonFormat_(self, ann);
  return self;
}

- (instancetype)initWithNSString:(NSString *)p
withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)sh
                    withNSString:(NSString *)localeStr
                    withNSString:(NSString *)tzStr {
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withNSString_withNSString_(self, p, sh, localeStr, tzStr);
  return self;
}

- (instancetype)initWithNSString:(NSString *)p
withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)sh
              withJavaUtilLocale:(JavaUtilLocale *)l
            withJavaUtilTimeZone:(JavaUtilTimeZone *)tz {
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withJavaUtilTimeZone_(self, p, sh, l, tz);
  return self;
}

- (instancetype)initWithNSString:(NSString *)p
withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)sh
              withJavaUtilLocale:(JavaUtilLocale *)l
                    withNSString:(NSString *)tzStr
            withJavaUtilTimeZone:(JavaUtilTimeZone *)tz {
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(self, p, sh, l, tzStr, tz);
  return self;
}

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withPatternWithNSString:(NSString *)p {
  return [new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(p, shape_, locale_, timezoneStr_, _timezone_) autorelease];
}

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withShapeWithComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:(ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)s {
  return [new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(pattern_, s, locale_, timezoneStr_, _timezone_) autorelease];
}

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withLocaleWithJavaUtilLocale:(JavaUtilLocale *)l {
  return [new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(pattern_, shape_, l, timezoneStr_, _timezone_) autorelease];
}

- (ComFasterxmlJacksonAnnotationJsonFormat_Value *)withTimeZoneWithJavaUtilTimeZone:(JavaUtilTimeZone *)tz {
  return [new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(pattern_, shape_, locale_, nil, tz) autorelease];
}

- (NSString *)getPattern {
  return pattern_;
}

- (ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *)getShape {
  return shape_;
}

- (JavaUtilLocale *)getLocale {
  return locale_;
}

- (NSString *)timeZoneAsString {
  if (_timezone_ != nil) {
    return [_timezone_ getID];
  }
  return timezoneStr_;
}

- (JavaUtilTimeZone *)getTimeZone {
  JavaUtilTimeZone *tz = _timezone_;
  if (tz == nil) {
    if (timezoneStr_ == nil) {
      return nil;
    }
    tz = JavaUtilTimeZone_getTimeZoneWithNSString_(timezoneStr_);
    ComFasterxmlJacksonAnnotationJsonFormat_Value_set__timezone_(self, tz);
  }
  return tz;
}

- (jboolean)hasShape {
  return shape_ != ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_get_ANY();
}

- (jboolean)hasPattern {
  return (pattern_ != nil) && (((jint) [pattern_ length]) > 0);
}

- (jboolean)hasLocale {
  return locale_ != nil;
}

- (jboolean)hasTimeZone {
  return (_timezone_ != nil) || (timezoneStr_ != nil && ![timezoneStr_ isEmpty]);
}

- (void)dealloc {
  RELEASE_(pattern_);
  RELEASE_(shape_);
  RELEASE_(locale_);
  RELEASE_(timezoneStr_);
  RELEASE_(_timezone_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Value", NULL, 0x1, NULL, NULL },
    { "initWithComFasterxmlJacksonAnnotationJsonFormat:", "Value", NULL, 0x1, NULL, NULL },
    { "initWithNSString:withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:withNSString:withNSString:", "Value", NULL, 0x1, NULL, NULL },
    { "initWithNSString:withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:withJavaUtilLocale:withJavaUtilTimeZone:", "Value", NULL, 0x1, NULL, NULL },
    { "initWithNSString:withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:withJavaUtilLocale:withNSString:withJavaUtilTimeZone:", "Value", NULL, 0x1, NULL, NULL },
    { "withPatternWithNSString:", "withPattern", "Lcom.fasterxml.jackson.annotation.JsonFormat$Value;", 0x1, NULL, NULL },
    { "withShapeWithComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum:", "withShape", "Lcom.fasterxml.jackson.annotation.JsonFormat$Value;", 0x1, NULL, NULL },
    { "withLocaleWithJavaUtilLocale:", "withLocale", "Lcom.fasterxml.jackson.annotation.JsonFormat$Value;", 0x1, NULL, NULL },
    { "withTimeZoneWithJavaUtilTimeZone:", "withTimeZone", "Lcom.fasterxml.jackson.annotation.JsonFormat$Value;", 0x1, NULL, NULL },
    { "getPattern", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getShape", NULL, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", 0x1, NULL, NULL },
    { "getLocale", NULL, "Ljava.util.Locale;", 0x1, NULL, NULL },
    { "timeZoneAsString", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getTimeZone", NULL, "Ljava.util.TimeZone;", 0x1, NULL, NULL },
    { "hasShape", NULL, "Z", 0x1, NULL, NULL },
    { "hasPattern", NULL, "Z", 0x1, NULL, NULL },
    { "hasLocale", NULL, "Z", 0x1, NULL, NULL },
    { "hasTimeZone", NULL, "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "pattern_", NULL, 0x12, "Ljava.lang.String;", NULL, NULL,  },
    { "shape_", NULL, 0x12, "Lcom.fasterxml.jackson.annotation.JsonFormat$Shape;", NULL, NULL,  },
    { "locale_", NULL, 0x12, "Ljava.util.Locale;", NULL, NULL,  },
    { "timezoneStr_", NULL, 0x12, "Ljava.lang.String;", NULL, NULL,  },
    { "_timezone_", NULL, 0x2, "Ljava.util.TimeZone;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationJsonFormat_Value = { 2, "Value", "com.fasterxml.jackson.annotation", "JsonFormat", 0x9, 18, methods, 5, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComFasterxmlJacksonAnnotationJsonFormat_Value;
}

@end

void ComFasterxmlJacksonAnnotationJsonFormat_Value_init(ComFasterxmlJacksonAnnotationJsonFormat_Value *self) {
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withNSString_withNSString_(self, @"", ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_get_ANY(), @"", @"");
}

ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_init() {
  ComFasterxmlJacksonAnnotationJsonFormat_Value *self = [ComFasterxmlJacksonAnnotationJsonFormat_Value alloc];
  ComFasterxmlJacksonAnnotationJsonFormat_Value_init(self);
  return self;
}

void ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithComFasterxmlJacksonAnnotationJsonFormat_(ComFasterxmlJacksonAnnotationJsonFormat_Value *self, id<ComFasterxmlJacksonAnnotationJsonFormat> ann) {
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withNSString_withNSString_(self, [((id<ComFasterxmlJacksonAnnotationJsonFormat>) nil_chk(ann)) pattern], [ann shape], [ann locale], [ann timezone]);
}

ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithComFasterxmlJacksonAnnotationJsonFormat_(id<ComFasterxmlJacksonAnnotationJsonFormat> ann) {
  ComFasterxmlJacksonAnnotationJsonFormat_Value *self = [ComFasterxmlJacksonAnnotationJsonFormat_Value alloc];
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithComFasterxmlJacksonAnnotationJsonFormat_(self, ann);
  return self;
}

void ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withNSString_withNSString_(ComFasterxmlJacksonAnnotationJsonFormat_Value *self, NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, NSString *localeStr, NSString *tzStr) {
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(self, p, sh, (localeStr == nil || ((jint) [localeStr length]) == 0 || [((NSString *) nil_chk(ComFasterxmlJacksonAnnotationJsonFormat_get_DEFAULT_LOCALE_())) isEqual:localeStr]) ? nil : [new_JavaUtilLocale_initWithNSString_(localeStr) autorelease], (tzStr == nil || ((jint) [tzStr length]) == 0 || [((NSString *) nil_chk(ComFasterxmlJacksonAnnotationJsonFormat_get_DEFAULT_TIMEZONE_())) isEqual:tzStr]) ? nil : tzStr, nil);
}

ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withNSString_withNSString_(NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, NSString *localeStr, NSString *tzStr) {
  ComFasterxmlJacksonAnnotationJsonFormat_Value *self = [ComFasterxmlJacksonAnnotationJsonFormat_Value alloc];
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withNSString_withNSString_(self, p, sh, localeStr, tzStr);
  return self;
}

void ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withJavaUtilTimeZone_(ComFasterxmlJacksonAnnotationJsonFormat_Value *self, NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, JavaUtilLocale *l, JavaUtilTimeZone *tz) {
  NSObject_init(self);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set_pattern_(self, p);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set_shape_(self, (sh == nil) ? ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_get_ANY() : sh);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set_locale_(self, l);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set__timezone_(self, tz);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set_timezoneStr_(self, nil);
}

ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withJavaUtilTimeZone_(NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, JavaUtilLocale *l, JavaUtilTimeZone *tz) {
  ComFasterxmlJacksonAnnotationJsonFormat_Value *self = [ComFasterxmlJacksonAnnotationJsonFormat_Value alloc];
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withJavaUtilTimeZone_(self, p, sh, l, tz);
  return self;
}

void ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(ComFasterxmlJacksonAnnotationJsonFormat_Value *self, NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, JavaUtilLocale *l, NSString *tzStr, JavaUtilTimeZone *tz) {
  NSObject_init(self);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set_pattern_(self, p);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set_shape_(self, (sh == nil) ? ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_get_ANY() : sh);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set_locale_(self, l);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set__timezone_(self, tz);
  ComFasterxmlJacksonAnnotationJsonFormat_Value_set_timezoneStr_(self, tzStr);
}

ComFasterxmlJacksonAnnotationJsonFormat_Value *new_ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(NSString *p, ComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum *sh, JavaUtilLocale *l, NSString *tzStr, JavaUtilTimeZone *tz) {
  ComFasterxmlJacksonAnnotationJsonFormat_Value *self = [ComFasterxmlJacksonAnnotationJsonFormat_Value alloc];
  ComFasterxmlJacksonAnnotationJsonFormat_Value_initWithNSString_withComFasterxmlJacksonAnnotationJsonFormat_ShapeEnum_withJavaUtilLocale_withNSString_withJavaUtilTimeZone_(self, p, sh, l, tzStr, tz);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationJsonFormat_Value)
