//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonIdentityReference.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonIdentityReference_H_
#define _ComFasterxmlJacksonAnnotationJsonIdentityReference_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonIdentityReference < JavaLangAnnotationAnnotation >

@property (readonly) BOOL alwaysAsId;


@end

@interface ComFasterxmlJacksonAnnotationJsonIdentityReference : NSObject < ComFasterxmlJacksonAnnotationJsonIdentityReference > {
 @private
  BOOL alwaysAsId;
}

- (id)initWithAlwaysAsId:(BOOL)alwaysAsId_;

+ (BOOL)alwaysAsIdDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonIdentityReference_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonIdentityReference_H_
