//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonView.java
//
//  Created by blangel on 4/21/15.
//

#ifndef _ComFasterxmlJacksonAnnotationJsonView_H_
#define _ComFasterxmlJacksonAnnotationJsonView_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComFasterxmlJacksonAnnotationJsonView < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;


@end

@interface ComFasterxmlJacksonAnnotationJsonView : NSObject < ComFasterxmlJacksonAnnotationJsonView > {
 @private
  IOSObjectArray *value;
}

- (id)initWithValue:(IOSObjectArray *)value_;

+ (IOSObjectArray *)valueDefault;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationJsonView_init() {}

#endif // _ComFasterxmlJacksonAnnotationJsonView_H_
