//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/ubuntu/projects/jackson-annotations/target/src/com/fasterxml/jackson/annotation/JsonPropertyOrder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonPropertyOrder")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationJsonPropertyOrder
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonPropertyOrder 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonPropertyOrder 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationJsonPropertyOrder

#if !defined (ComFasterxmlJacksonAnnotationJsonPropertyOrder_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonPropertyOrder || defined(INCLUDE_ComFasterxmlJacksonAnnotationJsonPropertyOrder))
#define ComFasterxmlJacksonAnnotationJsonPropertyOrder_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class IOSObjectArray;

@protocol ComFasterxmlJacksonAnnotationJsonPropertyOrder < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;
@property (readonly) jboolean alphabetic;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface ComFasterxmlJacksonAnnotationJsonPropertyOrder : NSObject < ComFasterxmlJacksonAnnotationJsonPropertyOrder > {
 @public
  IOSObjectArray *value_;
  jboolean alphabetic_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationJsonPropertyOrder)

FOUNDATION_EXPORT id<ComFasterxmlJacksonAnnotationJsonPropertyOrder> create_ComFasterxmlJacksonAnnotationJsonPropertyOrder(jboolean alphabetic, IOSObjectArray *value);

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationJsonPropertyOrder)

#endif

#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationJsonPropertyOrder")
