//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/ObjectIdGenerator.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/ObjectIdGenerator.h"

#define ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_serialVersionUID 1LL

@interface ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey () {
 @public
  jint hashCode__;
}

@end

J2OBJC_STATIC_FIELD_GETTER(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey, serialVersionUID, jlong)

@implementation ComFasterxmlJacksonAnnotationObjectIdGenerator

- (IOSClass *)getScope {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (jboolean)canUseForWithComFasterxmlJacksonAnnotationObjectIdGenerator:(ComFasterxmlJacksonAnnotationObjectIdGenerator *)gen {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (jboolean)maySerializeAsObject {
  return NO;
}

- (jboolean)isValidReferencePropertyNameWithNSString:(NSString *)name
                                              withId:(id)parser {
  return NO;
}

- (ComFasterxmlJacksonAnnotationObjectIdGenerator *)forScopeWithIOSClass:(IOSClass *)scope {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (ComFasterxmlJacksonAnnotationObjectIdGenerator *)newForSerializationWithId:(id)context {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *)keyWithId:(id)key {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id)generateIdWithId:(id)forPojo {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (instancetype)init {
  ComFasterxmlJacksonAnnotationObjectIdGenerator_init(self);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getScope", NULL, "Ljava.lang.Class;", 0x401, NULL, NULL },
    { "canUseForWithComFasterxmlJacksonAnnotationObjectIdGenerator:", "canUseFor", "Z", 0x401, NULL, NULL },
    { "maySerializeAsObject", NULL, "Z", 0x1, NULL, NULL },
    { "isValidReferencePropertyNameWithNSString:withId:", "isValidReferencePropertyName", "Z", 0x1, NULL, NULL },
    { "forScopeWithIOSClass:", "forScope", "Lcom.fasterxml.jackson.annotation.ObjectIdGenerator;", 0x401, NULL, NULL },
    { "newForSerializationWithId:", "newForSerialization", "Lcom.fasterxml.jackson.annotation.ObjectIdGenerator;", 0x401, NULL, NULL },
    { "keyWithId:", "key", "Lcom.fasterxml.jackson.annotation.ObjectIdGenerator$IdKey;", 0x401, NULL, NULL },
    { "generateIdWithId:", "generateId", "TT;", 0x401, NULL, "(Ljava/lang/Object;)TT;" },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const char *inner_classes[] = {"Lcom.fasterxml.jackson.annotation.ObjectIdGenerator$IdKey;"};
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationObjectIdGenerator = { 2, "ObjectIdGenerator", "com.fasterxml.jackson.annotation", NULL, 0x401, 9, methods, 0, NULL, 0, NULL, 1, inner_classes, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;Ljava/io/Serializable;" };
  return &_ComFasterxmlJacksonAnnotationObjectIdGenerator;
}

@end

void ComFasterxmlJacksonAnnotationObjectIdGenerator_init(ComFasterxmlJacksonAnnotationObjectIdGenerator *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationObjectIdGenerator)

@implementation ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey

- (instancetype)initWithIOSClass:(IOSClass *)type
                    withIOSClass:(IOSClass *)scope
                          withId:(id)key {
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_initWithIOSClass_withIOSClass_withId_(self, type, scope, key);
  return self;
}

- (NSUInteger)hash {
  return hashCode__;
}

- (jboolean)isEqual:(id)o {
  if (o == self) return YES;
  if (o == nil) return NO;
  if ([nil_chk(o) getClass] != [self getClass]) return NO;
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *other = (ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *) check_class_cast(o, [ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey class]);
  return ([nil_chk(other->key_) isEqual:key_]) && (other->type_ == type_) && (other->scope_ == scope_);
}

- (void)dealloc {
  RELEASE_(type_);
  RELEASE_(scope_);
  RELEASE_(key_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithIOSClass:withIOSClass:withId:", "IdKey", NULL, 0x1, NULL, NULL },
    { "hash", "hashCode", "I", 0x1, NULL, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J", NULL, NULL, .constantValue.asLong = ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_serialVersionUID },
    { "type_", NULL, 0x11, "Ljava.lang.Class;", NULL, "Ljava/lang/Class<*>;",  },
    { "scope_", NULL, 0x11, "Ljava.lang.Class;", NULL, "Ljava/lang/Class<*>;",  },
    { "key_", NULL, 0x11, "Ljava.lang.Object;", NULL, NULL,  },
    { "hashCode__", "hashCode", 0x12, "I", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey = { 2, "IdKey", "com.fasterxml.jackson.annotation", "ObjectIdGenerator", 0x19, 3, methods, 5, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey;
}

@end

void ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_initWithIOSClass_withIOSClass_withId_(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *self, IOSClass *type, IOSClass *scope, id key) {
  NSObject_init(self);
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_type_(self, type);
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_scope_(self, scope);
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_key_(self, key);
  jint h = ((jint) [nil_chk(key) hash]) + ((jint) [((NSString *) nil_chk([((IOSClass *) nil_chk(type)) getName])) hash]);
  if (scope != nil) {
    h ^= ((jint) [((NSString *) nil_chk([scope getName])) hash]);
  }
  self->hashCode__ = h;
}

ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *new_ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_initWithIOSClass_withIOSClass_withId_(IOSClass *type, IOSClass *scope, id key) {
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *self = [ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey alloc];
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_initWithIOSClass_withIOSClass_withId_(self, type, scope, key);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey)
