//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/ObjectIdGenerator.java
//

#include "IOSClass.h"
#include "com/fasterxml/jackson/annotation/ObjectIdGenerator.h"

#pragma clang diagnostic ignored "-Wprotocol"
#pragma clang diagnostic ignored "-Wincomplete-implementation"

@implementation ComFasterxmlJacksonAnnotationObjectIdGenerator

- (jboolean)maySerializeAsObject {
  return NO;
}

- (jboolean)isValidReferencePropertyNameWithNSString:(NSString *)name
                                              withId:(id)parser {
  return NO;
}

- (instancetype)init {
  return [super init];
}

@end

@implementation ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey

- (instancetype)initWithIOSClass:(IOSClass *)type
                    withIOSClass:(IOSClass *)scope
                          withId:(id)key {
  if (self = [super init]) {
    ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_type_(self, type);
    ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_scope_(self, scope);
    ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_key_(self, key);
    jint h = ((jint) [nil_chk(key) hash]) + ((jint) [((NSString *) nil_chk([((IOSClass *) nil_chk(type)) getName])) hash]);
    if (scope != nil) {
      h ^= ((jint) [((NSString *) nil_chk([scope getName])) hash]);
    }
    hashCode__ = h;
  }
  return self;
}

- (NSUInteger)hash {
  return hashCode__;
}

- (jboolean)isEqual:(id)o {
  if (o == self) return YES;
  if (o == nil) return NO;
  if ([nil_chk(o) getClass] != [self getClass]) return NO;
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *other = (ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *) check_class_cast(o, [ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey class]);
  return ([nil_chk(other->key_) isEqual:key_]) && (other->type_ == type_) && (other->scope_ == scope_);
}

- (void)dealloc {
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_type_(self, nil);
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_scope_(self, nil);
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_key_(self, nil);
  [super dealloc];
}

- (void)copyAllFieldsTo:(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *)other {
  [super copyAllFieldsTo:other];
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_type_(other, type_);
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_scope_(other, scope_);
  ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_set_key_(other, key_);
  other->hashCode__ = hashCode__;
}

@end
