//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/dash/jackson-annotations/target/src/com/fasterxml/jackson/annotation/ObjectIdGenerator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdGenerator")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationObjectIdGenerator
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdGenerator 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdGenerator 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationObjectIdGenerator

#if !defined (ComFasterxmlJacksonAnnotationObjectIdGenerator_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdGenerator || defined(INCLUDE_ComFasterxmlJacksonAnnotationObjectIdGenerator))
#define ComFasterxmlJacksonAnnotationObjectIdGenerator_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey;
@class IOSClass;

@interface ComFasterxmlJacksonAnnotationObjectIdGenerator : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

- (jboolean)canUseForWithComFasterxmlJacksonAnnotationObjectIdGenerator:(ComFasterxmlJacksonAnnotationObjectIdGenerator *)gen;

- (ComFasterxmlJacksonAnnotationObjectIdGenerator *)forScopeWithIOSClass:(IOSClass *)scope;

- (id)generateIdWithId:(id)forPojo;

- (IOSClass *)getScope;

- (jboolean)isValidReferencePropertyNameWithNSString:(NSString *)name
                                              withId:(id)parser;

- (ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *)keyWithId:(id)key;

- (jboolean)maySerializeAsObject;

- (ComFasterxmlJacksonAnnotationObjectIdGenerator *)newForSerializationWithId:(id)context OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationObjectIdGenerator)

FOUNDATION_EXPORT void ComFasterxmlJacksonAnnotationObjectIdGenerator_init(ComFasterxmlJacksonAnnotationObjectIdGenerator *self);

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationObjectIdGenerator)

#endif

#if !defined (ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdGenerator || defined(INCLUDE_ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey))
#define ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class IOSClass;

@interface ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey : NSObject < JavaIoSerializable > {
 @public
  IOSClass *type_;
  IOSClass *scope_;
  id key_;
}

#pragma mark Public

- (instancetype)initWithIOSClass:(IOSClass *)type
                    withIOSClass:(IOSClass *)scope
                          withId:(id)key;

- (jboolean)isEqual:(id)o;

- (NSUInteger)hash;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey)

J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey, type_, IOSClass *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey, scope_, IOSClass *)
J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey, key_, id)

FOUNDATION_EXPORT void ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_initWithIOSClass_withIOSClass_withId_(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *self, IOSClass *type, IOSClass *scope, id key);

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *new_ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_initWithIOSClass_withIOSClass_withId_(IOSClass *type, IOSClass *scope, id key) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *create_ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey_initWithIOSClass_withIOSClass_withId_(IOSClass *type, IOSClass *scope, id key);

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey)

#endif

#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdGenerator")
