//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/dash/jackson-annotations/target/src/com/fasterxml/jackson/annotation/ObjectIdResolver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdResolver")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationObjectIdResolver
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdResolver 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdResolver 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationObjectIdResolver

#if !defined (ComFasterxmlJacksonAnnotationObjectIdResolver_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdResolver || defined(INCLUDE_ComFasterxmlJacksonAnnotationObjectIdResolver))
#define ComFasterxmlJacksonAnnotationObjectIdResolver_

@class ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey;

@protocol ComFasterxmlJacksonAnnotationObjectIdResolver < JavaObject >

- (void)bindItemWithComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey:(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *)id_
                                                                  withId:(id)pojo;

- (id)resolveIdWithComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey:(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *)id_;

- (id<ComFasterxmlJacksonAnnotationObjectIdResolver>)newForDeserializationWithId:(id)context OBJC_METHOD_FAMILY_NONE;

- (jboolean)canUseForWithComFasterxmlJacksonAnnotationObjectIdResolver:(id<ComFasterxmlJacksonAnnotationObjectIdResolver>)resolverType;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationObjectIdResolver)

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationObjectIdResolver)

#endif

#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationObjectIdResolver")
