//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/ObjectIdResolver.java
//

#ifndef _ComFasterxmlJacksonAnnotationObjectIdResolver_H_
#define _ComFasterxmlJacksonAnnotationObjectIdResolver_H_

@class ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey;

#import "JreEmulation.h"

@protocol ComFasterxmlJacksonAnnotationObjectIdResolver < NSObject, JavaObject >

- (void)bindItemWithComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey:(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *)id_
                                                                  withId:(id)pojo;

- (id)resolveIdWithComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey:(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *)id_;

- (id<ComFasterxmlJacksonAnnotationObjectIdResolver>)newForDeserializationWithId:(id)context OBJC_METHOD_FAMILY_NONE;

- (jboolean)canUseForWithComFasterxmlJacksonAnnotationObjectIdResolver:(id<ComFasterxmlJacksonAnnotationObjectIdResolver>)resolverType;

@end

__attribute__((always_inline)) inline void ComFasterxmlJacksonAnnotationObjectIdResolver_init() {}

#endif // _ComFasterxmlJacksonAnnotationObjectIdResolver_H_
