//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/dash/jackson-annotations/target/src/com/fasterxml/jackson/annotation/package-info.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationPackage_info")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationPackage_info
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationPackage_info 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationPackage_info 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationPackage_info

#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationPackage_info")
