//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/PropertyAccessor.java
//


#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "com/fasterxml/jackson/annotation/PropertyAccessor.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"

__attribute__((unused)) static void ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationPropertyAccessorEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static ComFasterxmlJacksonAnnotationPropertyAccessorEnum *new_ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

J2OBJC_INITIALIZED_DEFN(ComFasterxmlJacksonAnnotationPropertyAccessorEnum)

ComFasterxmlJacksonAnnotationPropertyAccessorEnum *ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values_[7];

@implementation ComFasterxmlJacksonAnnotationPropertyAccessorEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

- (jboolean)creatorEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_CREATOR) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

- (jboolean)getterEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_GETTER) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

- (jboolean)isGetterEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_IS_GETTER) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

- (jboolean)setterEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_SETTER) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

- (jboolean)fieldEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_FIELD) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

IOSObjectArray *ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values() {
  ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initialize();
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values_ count:7 type:ComFasterxmlJacksonAnnotationPropertyAccessorEnum_class_()];
}

+ (IOSObjectArray *)values {
  return ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values();
}

+ (ComFasterxmlJacksonAnnotationPropertyAccessorEnum *)valueOfWithNSString:(NSString *)name {
  return ComFasterxmlJacksonAnnotationPropertyAccessorEnum_valueOfWithNSString_(name);
}

ComFasterxmlJacksonAnnotationPropertyAccessorEnum *ComFasterxmlJacksonAnnotationPropertyAccessorEnum_valueOfWithNSString_(NSString *name) {
  ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initialize();
  for (int i = 0; i < 7; i++) {
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum *e = ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationPropertyAccessorEnum class]) {
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_GETTER = new_ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(@"GETTER", 0);
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_SETTER = new_ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(@"SETTER", 1);
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_CREATOR = new_ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(@"CREATOR", 2);
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_FIELD = new_ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(@"FIELD", 3);
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_IS_GETTER = new_ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(@"IS_GETTER", 4);
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_NONE = new_ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(@"NONE", 5);
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL = new_ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(@"ALL", 6);
    J2OBJC_SET_INITIALIZED(ComFasterxmlJacksonAnnotationPropertyAccessorEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "creatorEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "getterEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "isGetterEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "setterEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "fieldEnabled", NULL, "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "GETTER", "GETTER", 0x4019, "Lcom.fasterxml.jackson.annotation.PropertyAccessor;", &ComFasterxmlJacksonAnnotationPropertyAccessorEnum_GETTER, NULL,  },
    { "SETTER", "SETTER", 0x4019, "Lcom.fasterxml.jackson.annotation.PropertyAccessor;", &ComFasterxmlJacksonAnnotationPropertyAccessorEnum_SETTER, NULL,  },
    { "CREATOR", "CREATOR", 0x4019, "Lcom.fasterxml.jackson.annotation.PropertyAccessor;", &ComFasterxmlJacksonAnnotationPropertyAccessorEnum_CREATOR, NULL,  },
    { "FIELD", "FIELD", 0x4019, "Lcom.fasterxml.jackson.annotation.PropertyAccessor;", &ComFasterxmlJacksonAnnotationPropertyAccessorEnum_FIELD, NULL,  },
    { "IS_GETTER", "IS_GETTER", 0x4019, "Lcom.fasterxml.jackson.annotation.PropertyAccessor;", &ComFasterxmlJacksonAnnotationPropertyAccessorEnum_IS_GETTER, NULL,  },
    { "NONE", "NONE", 0x4019, "Lcom.fasterxml.jackson.annotation.PropertyAccessor;", &ComFasterxmlJacksonAnnotationPropertyAccessorEnum_NONE, NULL,  },
    { "ALL", "ALL", 0x4019, "Lcom.fasterxml.jackson.annotation.PropertyAccessor;", &ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL, NULL,  },
  };
  static const char *superclass_type_args[] = {"Lcom.fasterxml.jackson.annotation.PropertyAccessor;"};
  static const J2ObjcClassInfo _ComFasterxmlJacksonAnnotationPropertyAccessorEnum = { 2, "PropertyAccessor", "com.fasterxml.jackson.annotation", NULL, 0x4011, 5, methods, 7, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lcom/fasterxml/jackson/annotation/PropertyAccessor;>;" };
  return &_ComFasterxmlJacksonAnnotationPropertyAccessorEnum;
}

@end

void ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(ComFasterxmlJacksonAnnotationPropertyAccessorEnum *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

ComFasterxmlJacksonAnnotationPropertyAccessorEnum *new_ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  ComFasterxmlJacksonAnnotationPropertyAccessorEnum *self = [ComFasterxmlJacksonAnnotationPropertyAccessorEnum alloc];
  ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComFasterxmlJacksonAnnotationPropertyAccessorEnum)
