//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/PropertyAccessor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationPropertyAccessor")
#ifdef RESTRICT_ComFasterxmlJacksonAnnotationPropertyAccessor
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationPropertyAccessor 0
#else
#define INCLUDE_ALL_ComFasterxmlJacksonAnnotationPropertyAccessor 1
#endif
#undef RESTRICT_ComFasterxmlJacksonAnnotationPropertyAccessor

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComFasterxmlJacksonAnnotationPropertyAccessor_) && (INCLUDE_ALL_ComFasterxmlJacksonAnnotationPropertyAccessor || defined(INCLUDE_ComFasterxmlJacksonAnnotationPropertyAccessor))
#define ComFasterxmlJacksonAnnotationPropertyAccessor_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComFasterxmlJacksonAnnotationPropertyAccessor_Enum) {
  ComFasterxmlJacksonAnnotationPropertyAccessor_Enum_GETTER = 0,
  ComFasterxmlJacksonAnnotationPropertyAccessor_Enum_SETTER = 1,
  ComFasterxmlJacksonAnnotationPropertyAccessor_Enum_CREATOR = 2,
  ComFasterxmlJacksonAnnotationPropertyAccessor_Enum_FIELD = 3,
  ComFasterxmlJacksonAnnotationPropertyAccessor_Enum_IS_GETTER = 4,
  ComFasterxmlJacksonAnnotationPropertyAccessor_Enum_NONE = 5,
  ComFasterxmlJacksonAnnotationPropertyAccessor_Enum_ALL = 6,
};

@interface ComFasterxmlJacksonAnnotationPropertyAccessor : JavaLangEnum

#pragma mark Public

- (jboolean)creatorEnabled;

- (jboolean)fieldEnabled;

- (jboolean)getterEnabled;

- (jboolean)isGetterEnabled;

- (jboolean)setterEnabled;

+ (ComFasterxmlJacksonAnnotationPropertyAccessor *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

@end

J2OBJC_STATIC_INIT(ComFasterxmlJacksonAnnotationPropertyAccessor)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_values_[];

inline ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_get_GETTER();
J2OBJC_ENUM_CONSTANT(ComFasterxmlJacksonAnnotationPropertyAccessor, GETTER)

inline ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_get_SETTER();
J2OBJC_ENUM_CONSTANT(ComFasterxmlJacksonAnnotationPropertyAccessor, SETTER)

inline ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_get_CREATOR();
J2OBJC_ENUM_CONSTANT(ComFasterxmlJacksonAnnotationPropertyAccessor, CREATOR)

inline ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_get_FIELD();
J2OBJC_ENUM_CONSTANT(ComFasterxmlJacksonAnnotationPropertyAccessor, FIELD)

inline ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_get_IS_GETTER();
J2OBJC_ENUM_CONSTANT(ComFasterxmlJacksonAnnotationPropertyAccessor, IS_GETTER)

inline ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_get_NONE();
J2OBJC_ENUM_CONSTANT(ComFasterxmlJacksonAnnotationPropertyAccessor, NONE)

inline ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_get_ALL();
J2OBJC_ENUM_CONSTANT(ComFasterxmlJacksonAnnotationPropertyAccessor, ALL)

FOUNDATION_EXPORT IOSObjectArray *ComFasterxmlJacksonAnnotationPropertyAccessor_values();

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationPropertyAccessor *ComFasterxmlJacksonAnnotationPropertyAccessor_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationPropertyAccessor)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComFasterxmlJacksonAnnotationPropertyAccessor")
