//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/PropertyAccessor.java
//

#include "IOSClass.h"
#include "com/fasterxml/jackson/annotation/PropertyAccessor.h"
#include "java/lang/IllegalArgumentException.h"

BOOL ComFasterxmlJacksonAnnotationPropertyAccessorEnum_initialized = NO;

ComFasterxmlJacksonAnnotationPropertyAccessorEnum *ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values_[7];

@implementation ComFasterxmlJacksonAnnotationPropertyAccessorEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  return [super initWithNSString:__name withInt:__ordinal];
}

- (jboolean)creatorEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_CREATOR) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

- (jboolean)getterEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_GETTER) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

- (jboolean)isGetterEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_IS_GETTER) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

- (jboolean)setterEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_SETTER) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

- (jboolean)fieldEnabled {
  return (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_FIELD) || (self == ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL);
}

FOUNDATION_EXPORT IOSObjectArray *ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values() {
  return [IOSObjectArray arrayWithObjects:ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values_ count:7 type:[IOSClass classWithClass:[ComFasterxmlJacksonAnnotationPropertyAccessorEnum class]]];
}
+ (IOSObjectArray *)values {
  return ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values();
}

+ (ComFasterxmlJacksonAnnotationPropertyAccessorEnum *)valueOfWithNSString:(NSString *)name {
  return ComFasterxmlJacksonAnnotationPropertyAccessorEnum_valueOfWithNSString_(name);
}

ComFasterxmlJacksonAnnotationPropertyAccessorEnum *ComFasterxmlJacksonAnnotationPropertyAccessorEnum_valueOfWithNSString_(NSString *name) {
  for (int i = 0; i < 7; i++) {
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum *e = ComFasterxmlJacksonAnnotationPropertyAccessorEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [ComFasterxmlJacksonAnnotationPropertyAccessorEnum class]) {
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_GETTER = [[ComFasterxmlJacksonAnnotationPropertyAccessorEnum alloc] initWithNSString:@"GETTER" withInt:0];
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_SETTER = [[ComFasterxmlJacksonAnnotationPropertyAccessorEnum alloc] initWithNSString:@"SETTER" withInt:1];
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_CREATOR = [[ComFasterxmlJacksonAnnotationPropertyAccessorEnum alloc] initWithNSString:@"CREATOR" withInt:2];
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_FIELD = [[ComFasterxmlJacksonAnnotationPropertyAccessorEnum alloc] initWithNSString:@"FIELD" withInt:3];
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_IS_GETTER = [[ComFasterxmlJacksonAnnotationPropertyAccessorEnum alloc] initWithNSString:@"IS_GETTER" withInt:4];
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_NONE = [[ComFasterxmlJacksonAnnotationPropertyAccessorEnum alloc] initWithNSString:@"NONE" withInt:5];
    ComFasterxmlJacksonAnnotationPropertyAccessorEnum_ALL = [[ComFasterxmlJacksonAnnotationPropertyAccessorEnum alloc] initWithNSString:@"ALL" withInt:6];
    J2OBJC_SET_INITIALIZED(ComFasterxmlJacksonAnnotationPropertyAccessorEnum)
  }
}

@end
