//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/blangel/projects/3rd-party/jackson-annotations/target/src/com/fasterxml/jackson/annotation/SimpleObjectIdResolver.java
//

#ifndef _ComFasterxmlJacksonAnnotationSimpleObjectIdResolver_H_
#define _ComFasterxmlJacksonAnnotationSimpleObjectIdResolver_H_

#include "J2ObjC_header.h"
#include "com/fasterxml/jackson/annotation/ObjectIdResolver.h"

@class ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey;
@protocol JavaUtilMap;

@interface ComFasterxmlJacksonAnnotationSimpleObjectIdResolver : NSObject < ComFasterxmlJacksonAnnotationObjectIdResolver > {
 @public
  id<JavaUtilMap> _items_;
}

#pragma mark Public

- (instancetype)init;

- (void)bindItemWithComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey:(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *)id_
                                                                  withId:(id)ob;

- (jboolean)canUseForWithComFasterxmlJacksonAnnotationObjectIdResolver:(id<ComFasterxmlJacksonAnnotationObjectIdResolver>)resolverType;

- (id<ComFasterxmlJacksonAnnotationObjectIdResolver>)newForDeserializationWithId:(id)context OBJC_METHOD_FAMILY_NONE;

- (id)resolveIdWithComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey:(ComFasterxmlJacksonAnnotationObjectIdGenerator_IdKey *)id_;

@end

J2OBJC_EMPTY_STATIC_INIT(ComFasterxmlJacksonAnnotationSimpleObjectIdResolver)

J2OBJC_FIELD_SETTER(ComFasterxmlJacksonAnnotationSimpleObjectIdResolver, _items_, id<JavaUtilMap>)

FOUNDATION_EXPORT void ComFasterxmlJacksonAnnotationSimpleObjectIdResolver_init(ComFasterxmlJacksonAnnotationSimpleObjectIdResolver *self);

FOUNDATION_EXPORT ComFasterxmlJacksonAnnotationSimpleObjectIdResolver *new_ComFasterxmlJacksonAnnotationSimpleObjectIdResolver_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComFasterxmlJacksonAnnotationSimpleObjectIdResolver)

#endif // _ComFasterxmlJacksonAnnotationSimpleObjectIdResolver_H_
